version: '3.5'

services:
  mds-logstash:
    build:
      context: logstash/
      args:
        - ES_VERSION=${ES_VERSION}
    container_name: mds-logstash
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      ES_HOST: ${ES_HOST}
      ES_USER: ${ES_USER}
      ES_PASSWORD: ${ES_PASSWORD}
    ports:
      - "5044:5044"
    networks:
      - mds
    volumes:
      - ./logstash/test:/usr/share/logstash/monitor
    restart: always
networks:
  mds:
    driver: bridge