apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: certbot
  name: certbot-minespace
spec:
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata: null
    spec:
      activeDeadlineSeconds: 300
      backoffLimit: 6
      completions: 1
      parallelism: 1
      template:
        metadata:
          labels:
            app: certbot
        spec:
          containers:
          - env:
            - name: CERTBOT_EMAIL
              value: mds@gov.bc.ca
            - name: CERTBOT_DEBUG
              value: "false"
            - name: CERTBOT_DELETE_ACME_ROUTES
              value: "true"
            - name: CERTBOT_STAGING
              value: "false"
            - name: CERTBOT_DRY_RUN
              value: "false"
            - name: CERTBOT_SERVER
              value: https://acme-v02.api.letsencrypt.org/directory
            - name: APPLICATION_NAME
              value: minespace
            image: image-registry.openshift-image-registry.svc:5000/4c2ba9-tools/certbot:latest
            imagePullPolicy: Always
            name: certbot-minespace
            resources:
              limits:
                cpu: 250m
              requests:
                cpu: 50m
            volumeMounts:
            - mountPath: /etc/letsencrypt
              name: certbot-config
          restartPolicy: Never
          serviceAccountName: certbot
          volumes:
          - name: certbot-config
            persistentVolumeClaim:
              claimName: certbot-minespace
  schedule: 10 */12 * * *
  startingDeadlineSeconds: 60
  successfulJobsHistoryLimit: 3
  suspend: true