apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: certbot
  name: certbot-minespace
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: netapp-file-standard