apiVersion: authorization.openshift.io/v1
groupNames: null
kind: RoleBinding
metadata:
  labels:
    app: certbot
  name: certbot_edit
roleRef:
  name: edit
subjects:
- kind: ServiceAccount
  name: certbot