kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: certbot_pulling
rules:
  - verbs:
      - update
      - list
      - patch
      - get
    apiGroups:
      - image.openshift.io
    resources:
      - imagestreams
  - verbs:
      - get
      - update
    apiGroups:
      - ''
      - image.openshift.io
    resources:
      - imagestreams/layers