version: "2"
checks:
  argument-count:
    config:
      threshold: 10
  complex-logic:
    config:
      threshold: 10
  file-lines:
    config:
      threshold: 500
  method-complexity:
    config:
      threshold: 20
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 150
  nested-control-flow:
    config:
      threshold: 7
  return-statements:
    config:
      threshold: 6
  similar-code:
    enabled: false
  identical-code:
    enabled: false
