version: "3"

services:
  ####################### Flyway Migration Verification Definition #######################
  # Used to verify return code of migrations
  # TODO: replace these by setting up pipeline ENV for assign perm template migration
  flyway-verify:
    container_name: mds_flyway_verify
    build:
      context: migrations
      dockerfile: Dockerfile.flyway.dev
    environment:
      - FLYWAY_USER=mds
      - FLYWAY_HOME=/flyway
      - FLYWAY_PASSWORD=test
      - FLYWAY_DB_NAME=mds
      - FLYWAY_DB_HOST=postgres-verify
      - FLYWAY_URL=jdbc:postgresql://postgres-verify/mds
      - FLYWAY_OUT_OF_ORDER=true
      - FLYWAY_CONNECT_RETRIES=60
      - PLATFORM=ci
    depends_on:
      - postgres-verify

  ####################### Postgres Verification Definition #######################
  postgres-verify:
    restart: always
    container_name: mds_postgres_verify
    build:
      context: services/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=mds
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=mds
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 10

  ####################### Postgres Definition #######################
  postgres:
    restart: always
    container_name: mds_postgres
    build:
      context: services/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=mds
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=mds
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 10

  ####################### Flyway Migration Definition #######################
  flyway:
    container_name: mds_flyway
    build:
      context: migrations
      dockerfile: Dockerfile.flyway.dev
    environment:
      - FLYWAY_USER=mds
      - FLYWAY_HOME=/flyway
      - FLYWAY_PASSWORD=test
      - FLYWAY_DB_NAME=mds_test
      - FLYWAY_DB_HOST=postgres
      - FLYWAY_URL=jdbc:postgresql://postgres/mds_test
      - FLYWAY_OUT_OF_ORDER=true
      - FLYWAY_CONNECT_RETRIES=60
      - PLATFORM=ci
    depends_on:
      - postgres

  ####################### Backend Definition #######################
  backend:
    user: root:root # use root in ci as backend coverage file is initially created outside app/
    restart: always
    container_name: mds_backend
    build:
      context: services/core-api
    env_file: services/core-api/.env-example
    ports:
      - 5000:5000
    volumes:
      - ./services/core-api/:/app/
      - core_api_logs:/var/log/core-api/
    depends_on:
      - flyway
      - docgen-api

  ####################### Redis Definition #######################
  redis:
    image: redis:3.2-alpine
    container_name: mds_cache
    restart: always
    command: redis-server --requirepass redis-password
    ports:
      - "6379:6379"

  ####################### Frontend Definition #######################
  frontend:
    restart: always
    container_name: mds_frontend
    build:
      context: services/core-web
    command: [ "npm", "run", "serve" ]
    volumes:
      - ./services/core-web/src/:/app/src/
    ports:
      - 3000:3000
    env_file: ./services/core-web/.env-example

  ####################### MineSpace Definition #######################
  minespace:
    restart: always
    container_name: mds_minespace
    build:
      context: services/minespace-web
    command: [ "npm", "run", "serve" ]
    volumes:
      - ./services/minespace-web/src/:/app/src/
    ports:
      - 3020:3020
    env_file: ./services/minespace-web/.env-example

  ####################### DOCUMENT_GENERATION Definition #######################
  docgen-api:
    restart: always
    container_name: docgen_api
    image: bcgovimages/common-document-generation-service:2.4.1
    command: [ "npm", "run", "start" ]
    environment:
      - SERVER_PORT=3030
      - APP_PORT=3030
      - CACHE_DIR=/tmp/tmp-reports
      - NODE_ENV=development
    ports:
      - 3030:3030

####################### Networks Definition ######################
networks:
  default:
    driver: "bridge"

####################### Volumes Definition #######################
volumes:
  postgres_data: {}
  core_api_logs: {}
  core_web_logs: {}
