version: "3"

services:

  ####################### Keycloak for Cypress #######################
  keycloak:
    image: jboss/keycloak
  ####################### Open Telemetry #######################

  ####################### Postgres Definition #######################
  postgres:
    image: image-registry.apps.silver.devops.gov.bc.ca/4c2ba9-tools/postgres:13
  ####################### Flyway Migration Definition #######################
  flyway:
    image: image-registry.apps.silver.devops.gov.bc.ca/4c2ba9-tools/flyway:dev
  ####################### Backend Definition #######################
  backend:
    image: image-registry.apps.silver.devops.gov.bc.ca/4c2ba9-tools/backend:dev
  core_api_celery:
    image: image-registry.apps.silver.devops.gov.bc.ca/4c2ba9-tools/backend:dev

  ####################### TUSD Definition #######################
  tusd:
    image: image-registry.apps.silver.devops.gov.bc.ca/4c2ba9-tools/tusd:dev


  ####################### DOCUMENT_MANAGER_BACKEND Definition #######################
  document_manager_backend:
    image: image-registry.apps.silver.devops.gov.bc.ca/4c2ba9-tools/docman:dev

  document_manager_celery:
    image: image-registry.apps.silver.devops.gov.bc.ca/4c2ba9-tools/docman:dev

  document_manager_migrate:
    image: image-registry.apps.silver.devops.gov.bc.ca/4c2ba9-tools/docman:dev

  ####################### DOCUMENT_GENERATION Definition #######################
  docgen-api:
    image: image-registry.apps.silver.devops.gov.bc.ca/4c2ba9-tools/docgen
