# GitOpsTeam - create this CRD in your tools namespace in order to enable
# Argo CD for your project
apiVersion: warden.devops.gov.bc.ca/v1alpha1
kind: GitOpsTeam
metadata:
  name: gitopsteam-4c2ba9
  namespace: 4c2ba9-tools
spec:
  # gitOpsMembers defines the git repo access (tenant-gitops-XYZ)
  # Note that users with repo access will have to accept an invitation from
  # GitHub to join the bcgov-c GitHub organization if they are not already
  # members.
  # -----------------------------------------------------------------------
  gitOpsMembers:
    # Full admin access to the repo, including repo deletion, adding of users
    # Recommended for people who need full access to the project, including
    # sensitive and destructive actions like managing security or deleting a
    # repository.
    admins:
      - vyasworks
      - wilson496

    # Recommended for contributors who actively push to your project.
    writers:

    # Recommended for project managers who need to manage the repository without
    # access to sensitive or destructive actions.
    maintainers:

    # Recommended for non-code contributors who want to view or discuss your
    # project.
    readers:
      - will-freshworks
      - matbusby-fw
      - hitankar-freshworks
      - fwkendall

    # Recommended for contributors who need to manage issues and pull requests
    # without write access.
    triage:

  # projectMembers defines access to the Argo CD UI
  # -----------------------------------------------
  projectMembers:
    # Project Maintainers have full access to the Argo CD Project, including the
    # ability create, edit, and delete Applications within the Project
    maintainers:
      - wilson496@github
      - vyasworks@github

    # Project Readers have read-only access to the Project in the Argo CD UI
    readers:
      - will-freshworks@github
      - matbusby-fw@github
      - hitankar-freshworks@github
      - fwkendall@github
