FROM python:3.12.12-bookworm

# Create working directory
RUN mkdir /app
WORKDIR /app

# Install the requirements
COPY requirements.txt .
RUN pip install "setuptools<70.0.0" wheel && pip install --no-cache-dir --no-build-isolation -r requirements.txt

# Run the server
EXPOSE 5500
CMD ["flask","db","upgrade"]