FROM node:10

# Create working directory
RUN mkdir /app
WORKDIR /app

# Install app dependencies
COPY package.json package-lock.json ./

RUN npm ci

COPY . .

RUN npm run build --max_old_space_size=4096

CMD ["node", "server.js" ]