kind: Template
apiVersion: v1
metadata:
  name: dsrp-backend-bc
  creationTimestamp: null
parameters:
  - name: NAME
    displayName: Name
    description: A suffix appended to all objects
    value: backend
  - name: TAG
    value: dev
  - name: SOURCE_CONTEXT_DIR
    value: services/dsrp-api
  - name: SOURCE_REPOSITORY_URL
    required: true
  - name: SOURCE_REPOSITORY_REF
    required: false
    value: master
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: rhscl-python-36-rhel7
      creationTimestamp: null
      annotations:
        description: Python Base Image
      labels:
        shared: "true"
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: 3.6.1-36
          annotations: null
          from:
            kind: DockerImage
            name: registry.access.redhat.com/rhscl/python-36-rhel7:1-36
          importPolicy: {}
          referencePolicy:
            type: Local
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}-base
      creationTimestamp: null
      annotations:
        description: Python Runtime Image
      labels:
        shared: "true"
    spec:
      lookupPolicy:
        local: false
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}
      creationTimestamp: null
      labels:
        shared: "true"
      annotations:
        description: Keeps track of changes in the application image
    spec:
      lookupPolicy:
        local: false
      tags: []
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${NAME}-base
      creationTimestamp: null
      labels: {}
      annotations: {}
    spec:
      successfulBuildsHistoryLimit: 5
      failedBuildsHistoryLimit: 5
      completionDeadlineSeconds: 1440
      triggers:
        - type: ImageChange
          imageChange: {}
        - type: ConfigChange
      runPolicy: SerialLatestOnly
      source:
        contextDir: openshift/docker-images/python-36
        type: Git
        git:
          uri: ${SOURCE_REPOSITORY_URL}
          ref: ${SOURCE_REPOSITORY_REF}
      strategy:
        type: Docker
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: rhscl-python-36-rhel7:3.6.1-36
          env: []
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}-base:${TAG}
      resources:
        limits:
          cpu: 500m
          memory: 2Gi
        requests:
          cpu: 250m
          memory: 1Gi
      postCommit: {}
      nodeSelector: null
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${NAME}
      creationTimestamp: null
      annotations:
        description: Defines how to build the application
    spec:
      successfulBuildsHistoryLimit: 5
      failedBuildsHistoryLimit: 5
      completionDeadlineSeconds: 600
      triggers:
        - type: ImageChange
        - type: ConfigChange
      runPolicy: SerialLatestOnly
      source:
        type: Git
        git:
          uri: ${SOURCE_REPOSITORY_URL}
          ref: ${SOURCE_REPOSITORY_REF}
        contextDir: ${SOURCE_CONTEXT_DIR}
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: ${NAME}-base:${TAG}
          env:
            - name: BUILD_LOGLEVEL
              value: "2"
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}:${TAG}
      resources:
        limits:
          cpu: "2"
          memory: 4Gi
        requests:
          cpu: "1"
          memory: 2Gi
      nodeSelector: null
