kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: cj-refresh-gis-export
spec:
  schedule: 30 02 * * *
  concurrencyPolicy: Replace
  suspend: false
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      parallelism: 1
      completions: 1
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - name: refresh
              image: image-registry.apps.silver.devops.gov.bc.ca/openshift/postgresql
              args:
                - /bin/sh
                - '-c'
                - >-
                  psql -d $DB_NAME -U $DB_USER -h $DB_HOST -c "REFRESH MATERIALIZED VIEW
                  $VIEW"
              env:
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: postgresql
                      key: database-user
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgresql
                      key: database-password
                - name: DB_HOST
                  valueFrom:
                    secretKeyRef:
                      name: refresh-gis
                      key: database-hostname
                - name: DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: postgresql
                      key: database-name
                - name: VIEW
                  valueFrom:
                    secretKeyRef:
                      name: refresh-gis
                      key: view-name
                  resources:
                    limits:
                      cpu: 512m
                      memory: 1Gi
                    requests:
                      cpu: 128m
                      memory: 256Mi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: Always
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
          activeDeadlineSeconds: 1200
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
