kind: Template
apiVersion: v1
metadata:
  name: mds-digdag-dc
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${NAME}
      annotations:
        description: Exposes and load balances the application pods
    spec:
      ports:
        - name: 8080-tcp
          protocol: TCP
          port: 8080
          targetPort: 8080
      selector:
        name: ${NAME}
      type: ClusterIP
      sessionAffinity: None
  - kind: Route
    apiVersion: v1
    metadata:
      name: ${NAME}
    spec:
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      path: /
      to:
        kind: Service
        name: ${NAME}
      port:
        targetPort: 8080-tcp
      wildcardPolicy: None
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: ${NAME}
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: ${SCHEDULER_PVC_SIZE}
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}
      creationTimestamp: null
      labels:
        shared: "true"
      annotations:
        description: Keeps track of changes in the application image
    spec:
      lookupPolicy:
        local: false
      tags: []
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${NAME}
    spec:
      strategy:
        type: Recreate
        maxSurge: 50%
        maxUnavailable: 0
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}
            from:
              kind: ImageStreamTag
              name: ${NAME}:${TAG}
      replicas: 1
      selector:
        name: ${NAME}
      template:
        metadata:
          name: ${NAME}
          labels:
            name: ${NAME}
        spec:
          containers:
            - name: ${NAME}
              image: " "
              ports:
                - containerPort: 8080
                  protocol: TCP
                - containerPort: 8081
                  protocol: TCP
              env:
                - name: ENVIRONMENT_NAME
                  value: ${ENVIRONMENT_NAME}
                - name: IMAGE_TAG
                  value: ${TAG}
                - name: NAMESPACE
                  value: 4c2ba9-${ENVIRONMENT_NAME}
                - name: KUBECONFIG
                  value: /app/kube_config
                - name: KEYCLOAK_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: ${DIGDAG_SECRET_NAME}
                      key: keycloak-client-secret
                - name: WEBHOOK_URL
                  valueFrom:
                    secretKeyRef:
                      name: ${WEBHOOK_SECRET_NAME}
                      key: mds-chatops-scheduler
                - name: KUBERNETES_MASTER
                  value: https://kubernetes.default:443
                - name: KUBERNETES_TRUST_CERTIFICATES
                  value: "true"
                - name: KEYCLOAK_DISCOVERY_URL
                  value: ${KEYCLOAK_DISCOVERY_URL}
                - name: KEYCLOAK_CLIENT_ID
                  value: central-scheduler
                - name: KEYCLOAK_ADMIN_ROLE
                  value: digdag_admin
                - name: KEYCLOAK_UPSTREAM_URL
                  value: http://localhost:8081
                - name: KEYCLOAK_REDIRECT_URL
                  value: ${CORE_DOMAIN}
              volumeMounts:
                - mountPath: /app/digdag-server
                  name: ${NAME}-data
              resources:
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
              terminationMessagePath: /dev/termination-log
              imagePullPolicy: IfNotPresent
              capabilities: {}
              livenessProbe:
                failureThreshold: 3
                initialDelaySeconds: 60
                periodSeconds: 10
                successThreshold: 1
                tcpSocket:
                  port: 8081
                timeoutSeconds: 1
              readinessProbe:
                failureThreshold: 3
                initialDelaySeconds: 60
                periodSeconds: 10
                successThreshold: 1
                tcpSocket:
                  port: 8081
                timeoutSeconds: 1
          volumes:
            - name: ${NAME}-data
              persistentVolumeClaim:
                claimName: ${NAME}
          restartPolicy: Always
          dnsPolicy: ClusterFirst
          serviceAccountName: digdag
          serviceAccount: digdag
parameters:
  - name: CPU_LIMIT
    value: 500m
  - name: MEMORY_LIMIT
    value: 2Gi
  - name: CPU_REQUEST
    value: 200m
  - name: MEMORY_REQUEST
    value: 1Gi
  - name: ENVIRONMENT_NAME
    value: dev
  - name: NAME
    displayName: Object names
    description: The name of the OpenShift objects.
    value: digdag
    required: true
  - name: DIGDAG_SECRET_NAME
    value: template.mds-digdag-secret
  - name: WEBHOOK_SECRET_NAME
    value: template.mds-rocket-chat-integrations
  - name: CORE_DOMAIN
    required: true
  - name: TAG
    required: true
  - name: NAMESPACE
    value: 4c2ba9-dev
  - name: KEYCLOAK_DISCOVERY_URL
    value: https://test.oidc.gov.bc.ca/auth/realms/mds/.well-known/openid-configuration
  - name: SCHEDULER_PVC_SIZE
    required: true
