kind: Template
apiVersion: v1
metadata:
  name: filesystem-provider-bc
  creationTimestamp: null
parameters:
  - name: NAME
    displayName: Name
    description: A name used for all objects
    value: filesystem-provider
  - name: TAG
    displayName: Name
    description: The output/built ImageStream tag names
    value: dev
  - name: SOURCE_CONTEXT_DIR
    value: services/filesystem-provider
  - name: SOURCE_REPOSITORY_URL
    required: true
  - name: SOURCE_REPOSITORY_REF
    required: false
    value: master
  - name: DOTNET_STARTUP_PROJECT
    displayName: DotNet Startup Project
    description: The path to the startup project for the .Net application.
    value: ej2-amazon-s3-aspcore-file-provider
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}-base
