kind: Template
apiVersion: v1
metadata:
  name: mds-filesystem-provider-dc
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${NAME}
      annotations:
        description: Exposes and load balances the application pods
    spec:
      ports:
        - name: 8080-tcp
          protocol: TCP
          port: 8080
          targetPort: 8080
      selector:
        name: ${NAME}
      type: ClusterIP
      sessionAffinity: None
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${NAME}
    spec:
      strategy:
        type: Recreate
        maxSurge: 50%
        maxUnavailable: 0
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}
            from:
              kind: ImageStreamTag
              name: ${NAME}:${TAG}
              namespace: 4c2ba9-tools
      replicas: 1
      selector:
        name: ${NAME}
      template:
        metadata:
          name: ${NAME}
          labels:
            name: ${NAME}
        spec:
          containers:
            - name: ${NAME}
              image: " "
              ports:
                - containerPort: 8080
                  protocol: TCP
              env:
                - name: ASPNETCORE_ENVIRONMENT
                  value: ${ASPNETCORE_ENVIRONMENT}
                - name: IMAGE_TAG
                  value: ${TAG}
                - name: S3_PREFIX
                  value: /
                - name: OBJECT_STORE_HOST
                  valueFrom:
                    secretKeyRef:
                      name: object-store-credentials
                      key: endpoint
                - name: OBJECT_STORE_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: object-store-credentials
                      key: key-id
                - name: OBJECT_STORE_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: object-store-credentials
                      key: secret-access-key
                - name: OBJECT_STORE_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: object-store-credentials
                      key: bucket-id
                - name: SYNCFUSION_LICENSE_KEY
                  valueFrom:
                    secretKeyRef:
                      name: syncfusion-license
                      key: license
                - name: JWT_OIDC_AUTHORITY
                  value: ${JWT_OIDC_AUTHORITY}
                - name: JWT_OIDC_AUDIENCE
                  value: ${JWT_OIDC_AUDIENCE}
              resources:
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
              imagePullPolicy: IfNotPresent
              livenessProbe:
                failureThreshold: 3
                initialDelaySeconds: 60
                periodSeconds: 10
                successThreshold: 1
                tcpSocket:
                  port: 8080
                timeoutSeconds: 1
              readinessProbe:
                failureThreshold: 3
                initialDelaySeconds: 60
                periodSeconds: 10
                successThreshold: 1
                tcpSocket:
                  port: 8080
                timeoutSeconds: 1
parameters:
  - name: CPU_LIMIT
    value: 500m
  - name: MEMORY_LIMIT
    value: 2Gi
  - name: CPU_REQUEST
    value: 200m
  - name: MEMORY_REQUEST
    value: 1Gi
  - name: ENVIRONMENT_NAME
    value: dev
  - name: NAME
    displayName: Object names
    description: The name of the OpenShift objects.
    value: filesystem-provider
    required: true
  - name: TAG
    required: true
  - name: ASPNETCORE_ENVIRONMENT
    displayName: AspNetCore Environment
    description: The ASP Net Core deployment environment setting.
    value: Development
  - name: JWT_OIDC_AUDIENCE
    displayName: Keycloak clientId
    required: true
  - name: JWT_OIDC_AUTHORITY
    displayName: Token issuer
    required: true
