kind: Template
apiVersion: v1
metadata:
  name: flyway
  creationTimestamp: null
parameters:
  - name: NAME
    displayName: Name
    description: A name used for all objects
    value: flyway
  - name: TAG
    displayName: Name
    description: The output/built ImageStream tag names
    value: dev
  - name: SOURCE_CONTEXT_DIR
    value: migrations
  - name: SOURCE_REPOSITORY_URL
    required: true
  - name: SOURCE_REPOSITORY_REF
    required: false
    value: master
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: openjdk18-openshift
      creationTimestamp: null
      labels:
        shared: "true"
      annotations: {}
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: 1.3-9
          from:
            kind: DockerImage
            name: registry.access.redhat.com/ubi8/openjdk-8:1.3-9
          importPolicy: {}
          referencePolicy:
            type: Local
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}
      creationTimestamp: null
      labels:
        shared: "true"
      annotations: {}
    spec:
      lookupPolicy:
        local: false
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${NAME}
      creationTimestamp: null
    spec:
      successfulBuildsHistoryLimit: 5
      failedBuildsHistoryLimit: 5
      completionDeadlineSeconds: 1440
      triggers:
        - type: ImageChange
          imageChange: {}
        - type: ConfigChange
      runPolicy: SerialLatestOnly
      source:
        contextDir: ${SOURCE_CONTEXT_DIR}
        git:
          ref: ${SOURCE_REPOSITORY_REF}
          uri: ${SOURCE_REPOSITORY_URL}
        type: Git
      strategy:
        type: Docker
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: openjdk18-openshift:1.3-9
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}:${TAG}
      resources:
        limits:
          cpu: "1"
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 512Mi
