kind: Template
apiVersion: v1
metadata:
  name: dsrp-frontend-bc
  creationTimestamp: null
parameters:
  - name: NAME
    displayName: Name
    description: A suffix appended to all objects
    value: frontend
  - name: TAG
    value: dev
  - name: BASE_PATH
    required: false
    value: ""
  - name: DOCKER_IMAGE_DIRECTORY
    value: openshift/docker-images/nodejs-10
  - name: SOURCE_CONTEXT_DIR
    value: services/dsrp-web
  - name: SOURCE_REPOSITORY_URL
    required: true
  - name: SOURCE_REPOSITORY_REF
    required: false
    value: master
  - name: NODE_ENV
    displayName: Node Environment
    description: Environment for running node
    value: production
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: redhat-ubi-node-10
      creationTimestamp: null
      annotations:
        description: Nodejs Base Image
      labels:
        shared: "true"
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: latest
          annotations: null
          from:
            kind: DockerImage
            name: registry.access.redhat.com/ubi8/nodejs-10:latest
          importPolicy: {}
          referencePolicy:
            type: Local
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}-base
      creationTimestamp: null
      annotations:
        description: Nodejs Runtime Image
      labels:
        shared: "true"
    spec:
      lookupPolicy:
        local: false
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}
      creationTimestamp: null
      labels: {}
      annotations:
        description: Keeps track of changes in the application image
    spec:
      lookupPolicy:
        local: false
      tags: []
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${NAME}-base
      creationTimestamp: null
      labels: {}
      annotations: {}
    spec:
      successfulBuildsHistoryLimit: 5
      failedBuildsHistoryLimit: 5
      completionDeadlineSeconds: 1440
      triggers:
        - type: ImageChange
          imageChange: {}
        - type: ConfigChange
      runPolicy: SerialLatestOnly
      source:
        contextDir: ${DOCKER_IMAGE_DIRECTORY}
        type: Git
        git:
          uri: ${SOURCE_REPOSITORY_URL}
          ref: ${SOURCE_REPOSITORY_REF}
      strategy:
        type: Docker
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: redhat-ubi-node-10:latest
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}-base:${TAG}
      resources:
        limits:
          cpu: "2"
          memory: 4Gi
        requests:
          cpu: "1"
          memory: 2Gi
      postCommit: {}
      nodeSelector: null
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${NAME}
      creationTimestamp: null
      labels: {}
      annotations:
        description: Defines how to build the application
    spec:
      successfulBuildsHistoryLimit: 5
      failedBuildsHistoryLimit: 5
      completionDeadlineSeconds: 900
      triggers:
        - type: ImageChange
        - type: ConfigChange
      runPolicy: SerialLatestOnly
      source:
        type: Git
        git:
          uri: ${SOURCE_REPOSITORY_URL}
          ref: ${SOURCE_REPOSITORY_REF}
        contextDir: ${SOURCE_CONTEXT_DIR}
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: ${NAME}-base:${TAG}
          env:
            - name: BASE_PATH
              value: ${BASE_PATH}
            - name: ASSET_PATH
              value: ${BASE_PATH}/
            - name: SKIP_NPM_INSTALL
              value: "true"
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}:${TAG}
      resources:
        limits:
          cpu: "2"
          memory: 4Gi
        requests:
          cpu: "1"
          memory: 2Gi
      nodeSelector: null
