kind: Template
apiVersion: v1
metadata:
  name: dsrp-metabase-bc
  creationTimestamp: null
parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the objects defined in this template.
    required: true
    value: metabase
  - name: TAG
    required: true
  - name: SOURCE_REPOSITORY_URL
    required: true
  - name: SOURCE_REPOSITORY_REF
    required: false
    value: master
  - name: SOURCE_CONTEXT_DIR
    displayName: Source Context Directory
    description: The source context directory.
    required: false
    value: openshift/docker-images/metabase
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: openjdk
      creationTimestamp: null
      labels:
        shared: "true"
    spec:
      lookupPolicy:
        local: false
      # tags:
      #   - name: 8-jdk-alpine
      #     annotations: null
      #     from:
      #       kind: DockerImage
      #       name: openjdk:8-jdk-alpine
      #     importPolicy: {}
      #     referencePolicy:
      #       type: Local
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}
      creationTimestamp: null
      labels:
        shared: "true"
      annotations:
        description: Keeps track of changes in the application image
    spec:
      lookupPolicy:
        local: false
      tags: []
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        app: ${NAME}
        buildconfig: ${NAME}
    spec:
      successfulBuildsHistoryLimit: 5
      failedBuildsHistoryLimit: 5
      source:
        type: Git
        git:
          uri: ${SOURCE_REPOSITORY_URL}
          ref: ${SOURCE_REPOSITORY_REF}
        contextDir: ${SOURCE_CONTEXT_DIR}
      strategy:
        type: Docker
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: openjdk:8-jdk-alpine
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}:${TAG}
      completionDeadlineSeconds: 1440
      triggers:
        - type: ConfigChange
        - type: ImageChange
