kind: Template
apiVersion: v1
metadata:
  name: dsrp-metabase-postgres-bc
  creationTimestamp: null
parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the objects defined in this template.
    required: true
    value: metabase-postgres
  - name: TAG
    required: true
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}
      creationTimestamp: null
      labels:
        shared: "true"
      annotations:
        template.alpha.openshift.io/wait-for-ready: "true"
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: ${TAG}
          annotations: null
          from:
            kind: DockerImage
            name: registry.access.redhat.com/rhscl/postgresql-96-rhel7:1-53
          generation: 1
          importPolicy: {}
          referencePolicy:
            type: Local
