kind: Template
apiVersion: v1
metadata:
  name: mds-nginx-bc
  creationTimestamp: null
parameters:
  - name: NAME
    displayName: Name
    description: Build config name
    value: nginx
  - name: TAG
    value: dev
  - name: SOURCE_CONTEXT_DIR
    value: services/nginx
  - name: SOURCE_REPOSITORY_URL
    required: true
  - name: SOURCE_REPOSITORY_REF
    required: false
    value: master
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}
      creationTimestamp: null
      labels:
        shared: "true"
      annotations:
        description: Keeps track of changes in the application image
    spec:
      lookupPolicy:
        local: false
      tags: []
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${NAME}
      creationTimestamp: null
      annotations:
        description: Defines how to build the nginx image
    spec:
      successfulBuildsHistoryLimit: 5
      failedBuildsHistoryLimit: 5
      completionDeadlineSeconds: 1440
      triggers:
        - type: ImageChange
      runPolicy: SerialLatestOnly
      source:
        type: Git
        git:
          uri: ${SOURCE_REPOSITORY_URL}
          ref: ${SOURCE_REPOSITORY_REF}
        contextDir: ${SOURCE_CONTEXT_DIR}
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            namespace: 4c2ba9-tools
            name: bcgov-s2i-nginx:latest
          env:
            - name: NGINX_AUX_DIR
              value: auxiliary
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}:${TAG}
      nodeSelector: null
