kind: Template
apiVersion: v1
metadata:
  name: nris-etl-cronjob-template
  creationTimestamp: null
parameters:
  - name: NAME
    displayName: Name
    description: A name for all objects
    value: nris-etl
  - name: DB_CONFIG_NAME
    displayName: Database Config Name
    description: Configuration name for the database
    value: postgresql-nris
  - name: DB_HOST
    displayName: Database Host Name
    value: postgresql
  - name: TAG
    required: true
  - name: JWT_OIDC_WELL_KNOWN_CONFIG
    displayName: Keycloak config URL
    required: true
  - name: JWT_OIDC_AUDIENCE
    displayName: Keycloak clientId
    required: true
  - name: BASE_PATH
    required: false
    value: /
  - name: NRIS_ODB_CREDENTIALS
    required: false
    value: template.nris-odb-credentials
  - name: UWSGI_PROCESSES
    value: "2"
  - name: UWSGI_THREADS
    value: "4"
  - name: REPLICA_MIN
    value: "1"
  - name: REPLICA_MAX
    value: "1"
  - name: REDIS_CONFIG_NAME
    required: false
    value: template.redis-secret
  - name: CACHE_REDIS_HOST
    value: redis
  - name: ENVIRONMENT_NAME
    required: true
  - name: APPNAME
    displayName: AppName
    description: Application name for grouping pods in Openshift
    value: Core
objects:
  - kind: CronJob
    apiVersion: batch/v1beta1
    metadata:
      name: cj-${NAME}
      namespace: 4c2ba9-${TAG}
    spec:
      schedule: 05 01 * * *
      concurrencyPolicy: Replace
      suspend: false
      jobTemplate:
        metadata:
          name: ${NAME}-job
          creationTimestamp: null
        spec:
          parallelism: 1
          completions: 1
          template:
            metadata:
              creationTimestamp: null
              labels:
                parent: cj-${NAME}
            spec:
              volumes:
                - name: logs-volume
                  emptyDir: {}
                - name: odb-credentials
                  configMap:
                    name: 2021-odb-wallet
                    defaultMode: 420
              containers:
                - name: ${NAME}-job
                  image: >-
                    image-registry.apps.silver.devops.gov.bc.ca/4c2ba9-tools/nris:${TAG}
                  env:
                    - name: DB_USER
                      valueFrom:
                        secretKeyRef:
                          name: ${DB_CONFIG_NAME}
                          key: database-nris-user
                    - name: DB_HOST
                      value: ${DB_HOST}
                    - name: DB_PASS
                      valueFrom:
                        secretKeyRef:
                          name: ${DB_CONFIG_NAME}
                          key: database-nris-password
                    - name: DB_PORT
                      value: "5432"
                    - name: DB_NAME
                      valueFrom:
                        secretKeyRef:
                          name: ${DB_CONFIG_NAME}
                          key: database-name
                    - name: NRIS_DB_HOSTNAME
                      valueFrom:
                        secretKeyRef:
                          name: ${NRIS_ODB_CREDENTIALS}
                          key: db-host
                    - name: NRIS_DB_SERVICENAME
                      valueFrom:
                        secretKeyRef:
                          name: ${NRIS_ODB_CREDENTIALS}
                          key: db-service
                    - name: NRIS_DB_USER
                      valueFrom:
                        secretKeyRef:
                          name: ${NRIS_ODB_CREDENTIALS}
                          key: db-user
                    - name: NRIS_DB_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: ${NRIS_ODB_CREDENTIALS}
                          key: db-password
                    - name: NRIS_DB_PORT
                      valueFrom:
                        secretKeyRef:
                          name: ${NRIS_ODB_CREDENTIALS}
                          key: db-port
                    - name: NRIS_SERVER_CERT_DN
                      valueFrom:
                        secretKeyRef:
                          name: ${NRIS_ODB_CREDENTIALS}
                          key: db-server-cert-dn
                    - name: UWSGI_PROCESSES
                      value: ${UWSGI_PROCESSES}
                    - name: UWSGI_THREADS
                      value: ${UWSGI_THREADS}
                    - name: FLASK_RUN_PORT
                      value: "5500"
                    - name: FLASK_RUN_HOST
                      value: 0.0.0.0
                    - name: CACHE_REDIS_HOST
                      value: ${CACHE_REDIS_HOST}
                    - name: CACHE_REDIS_PASS
                      valueFrom:
                        secretKeyRef:
                          name: ${REDIS_CONFIG_NAME}
                          key: database-password
                    - name: JWT_OIDC_WELL_KNOWN_CONFIG
                      value: ${JWT_OIDC_WELL_KNOWN_CONFIG}
                    - name: JWT_OIDC_AUDIENCE
                      value: ${JWT_OIDC_AUDIENCE}
                    - name: JWT_OIDC_ALGORITHMS
                      value: RS256
                    - name: BASE_PATH
                      value: ${BASE_PATH}
                    - name: DOCUMENT_MANAGER_URL
                      value: ${API_URL}
                    - name: ENVIRONMENT_NAME
                      value: ${ENVIRONMENT_NAME}
                    - name: APP_FILE
                      value: /opt/app-root/src/run_etl.py
                    - name: ETL_MODE
                      value: "1"
                  resources:
                    limits:
                      cpu: 512m
                      memory: 4Gi
                    requests:
                      cpu: 256m
                      memory: 2Gi
                  volumeMounts:
                    - name: logs-volume
                      mountPath: /var/log
                    - name: odb-credentials
                      mountPath: /opt/app-root/src/wallet/cwallet.sso
                      subPath: cwallet.sso
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                  imagePullPolicy: IfNotPresent
              restartPolicy: Never
              terminationGracePeriodSeconds: 30
              activeDeadlineSeconds: 4200
              dnsPolicy: ClusterFirst
              securityContext: {}
              schedulerName: default-scheduler
      successfulJobsHistoryLimit: 5
      failedJobsHistoryLimit: 5
