kind: Template
apiVersion: v1
metadata:
  name: mds-python-oracle-bc
  creationTimestamp: null
parameters:
  - name: NAME
    displayName: Name
    description: A name used for all objects
    value: nris
  - name: TAG
    displayName: Name
    description: The output/built ImageStream tag names
    value: dev
  - name: SOURCE_CONTEXT_DIR
    value: services/nris-api/backend
  - name: SOURCE_REPOSITORY_URL
    required: true
  - name: SOURCE_REPOSITORY_REF
    required: false
    value: master
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: rhscl-python-36-rhel7
      creationTimestamp: null
      annotations:
        description: Python Base Image
      labels:
        shared: "true"
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: 3.6.1-73
          annotations: null
          from:
            kind: DockerImage
            name: registry.access.redhat.com/rhscl/python-36-rhel7:1-73
          importPolicy: {}
          referencePolicy:
            type: Local
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}-base
      creationTimestamp: null
      annotations:
        description: Python Runtime Image
      labels:
        shared: "true"
    spec:
      lookupPolicy:
        local: false
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}
      creationTimestamp: null
      labels:
        shared: "true"
      annotations:
        description: Keeps track of changes in the application image
    spec:
      lookupPolicy:
        local: false
      tags: []
