kind: Template
apiVersion: v1
metadata:
  name: postgresql
  creationTimestamp: null
parameters:
  - name: NAME
    displayName: Name
    description: A name used for all objects
    value: postgresql
  - name: TAG
    value: dev
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        shared: "true"
      annotations: {}
    spec:
      lookupPolicy:
        local: false
      tags:
        # - name: ${TAG}
        #   annotations: null
        #   from:
        #     kind: ImageStreamImage
        #     name: mds-postgresql:latest
        #     namespace: 4c2ba9-tools
        #   generation: 1
        #   importPolicy: {}
        #   referencePolicy:
        #     type: Source
