kind: Template
apiVersion: v1
metadata:
  name: postgresql
  creationTimestamp: null
parameters:
  - name: NAME
    displayName: Name
    description: A name used for all objects
    value: postgresql
  - name: TAG
    value: dev
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        shared: "true"
      annotations: {}
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: ${TAG}
          annotations: null
          from:
            kind: ImageStreamTag
            name: rhscl-postgres-10-rhel7:latest
            namespace: 4c2ba9-tools
          importPolicy: {}
          referencePolicy:
            type: Local
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}-base
      labels:
        shared: "true"
      annotations: {}
    spec:
      lookupPolicy:
        local: false

  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${NAME}-base
      creationTimestamp: null
      labels: {}
      annotations: {}
    spec:
      successfulBuildsHistoryLimit: 5
      failedBuildsHistoryLimit: 5
      completionDeadlineSeconds: 1440
      triggers:
        - type: ImageChange
          imageChange: {}
        - type: ConfigChange
      runPolicy: SerialLatestOnly
      source:
        contextDir: openshift/docker-images/postgres
        type: Git
        git:
          uri: ${SOURCE_REPOSITORY_URL}
          ref: ${SOURCE_REPOSITORY_REF}
      strategy:
        type: Docker
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: rhscl-postgres-10-rhel7:latest
          env: []
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}-base:${TAG}
      resources:
        limits:
          cpu: 250m
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 1Gi
      postCommit: {}
      nodeSelector: null
