kind: Template
apiVersion: v1
metadata:
  name: mds-tusd-bc
  creationTimestamp: null
parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the objects defined in this template.
    required: true
    value: tusd
  - name: SOURCE_REPOSITORY_URL
    displayName: Git Repo URL
    description: The URL to the Git repository.
    required: true
    value: https://github.com/bcgov/mds.git
  - name: TAG
    value: dev
  - name: SOURCE_REPOSITORY_REF
    displayName: Git Reference
    description: The git reference or branch.
    required: true
    value: master
  - name: SOURCE_CONTEXT_DIR
    displayName: Source Context Directory
    description: The source context directory.
    required: false
    value: openshift4/docker-images/tusd
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}-base
      creationTimestamp: null
      labels:
        shared: "true"
    spec:
      lookupPolicy:
        local: true
      tags:
        - name: v1.3.0
          annotations: null
          from:
            kind: DockerImage
            name: docker.io/tusproject/tusd:v1.3.0
          importPolicy: {}
          referencePolicy:
            type: Local
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}
      creationTimestamp: null
      labels:
        shared: "true"
    spec:
      lookupPolicy:
        local: false
      tags: []
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        app: ${NAME}
        buildconfig: ${NAME}
    spec:
      successfulBuildsHistoryLimit: 5
      failedBuildsHistoryLimit: 5
      source:
        type: Git
        git:
          uri: ${SOURCE_REPOSITORY_URL}
          ref: ${SOURCE_REPOSITORY_REF}
        contextDir: ${SOURCE_CONTEXT_DIR}
      strategy:
        type: Docker
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: tusd-base:v1.3.0
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}:${TAG}
      completionDeadlineSeconds: 600
      triggers:
        - type: ImageChange
