apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: mds-patroni
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: template
    app.kubernetes.io/name: patroni
    cluster-name: mds-patroni
  name: mds-patroni
