version: "2"

services:
  ####################### DIGDAG Definition #######################
  mds_scheduler:
    restart: always
    container_name: mds_scheduler
    build:
      context: ./
    volumes:
      - ./:/app/
    env_file: ./.env
    networks:
      - mds-scheduler
    ports:
      - 8080:8080
      - 8081:8081

####################### Networks Definition #######################
networks:
  mds-scheduler:
    driver: "bridge"
####################### Volumes Definition #######################

