"""empty message

Revision ID: 1ac2d5e5a073
Revises: c86eca21d297
Create Date: 2020-07-29 16:55:09.600039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ac2d5e5a073'
down_revision = 'c86eca21d297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inspection', 'business_area',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=10485760),
               existing_nullable=True)
    op.alter_column('inspection', 'inspector_idir',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=10485760),
               existing_nullable=True)
    op.alter_column('inspection', 'mine_no',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=10485760),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inspection', 'mine_no',
               existing_type=sa.String(length=10485760),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('inspection', 'inspector_idir',
               existing_type=sa.String(length=10485760),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
    op.alter_column('inspection', 'business_area',
               existing_type=sa.String(length=10485760),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###
