"""empty message

Revision ID: 1fe8a51229c4
Revises: afc90b53c158
Create Date: 2019-10-11 21:58:57.129679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fe8a51229c4'
down_revision = 'afc90b53c158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendee',
    sa.Column('attendee_id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('org', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspection.inspection_id'], ),
    sa.PrimaryKeyConstraint('attendee_id'),
    comment='Any attendee on an inspection.'
    )
    op.drop_table('Attendee')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Attendee',
    sa.Column('attendee_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Attendee_attendee_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('org', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('attendee_id', name='Attendee_pkey'),
    comment='Any attendee on an inspection.'
    )
    op.drop_table('attendee')
    # ### end Alembic commands ###
