"""empty message

Revision ID: 2db7d022d4f7
Revises: 1fe8a51229c4
Create Date: 2019-10-15 18:46:54.173471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2db7d022d4f7'
down_revision = '1fe8a51229c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendee', sa.Column('attendee_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'attendee', 'attendee_type', ['attendee_type_id'], ['attendee_type_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendee', type_='foreignkey')
    op.drop_column('attendee', 'attendee_type_id')
    # ### end Alembic commands ###
