"""empty message

Revision ID: 2e894e86b11c
Revises: 1ac2d5e5a073
Create Date: 2020-08-20 20:49:08.305646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e894e86b11c'
down_revision = '1ac2d5e5a073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspection', sa.Column('assessment_sub_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inspection', 'assessment_sub_type')
    # ### end Alembic commands ###
