"""empty message

Revision ID: ce5572d67c90
Revises: bf69217843fc
Create Date: 2019-05-27 18:58:22.038129

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ce5572d67c90'
down_revision = 'bf69217843fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection_type',
    sa.Column('inspection_type_id', sa.Integer(), nullable=False),
    sa.Column('inspection_type_code', sa.String(length=32), nullable=False),
    sa.Column('inspection_type_description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('inspection_type_id')
    )
    op.create_table('noncompliance_legislation',
    sa.Column('noncompliance_legislation_id', sa.Integer(), nullable=False),
    sa.Column('order_stop_detail_id', sa.Integer(), nullable=True),
    sa.Column('estimated_incident_date', sa.DateTime(), nullable=True),
    sa.Column('noncompliant_description', sa.String(length=256), nullable=True),
    sa.Column('parent_act_id', sa.Integer(), nullable=True),
    sa.Column('legislation_act_section_id', sa.Integer(), nullable=True),
    sa.Column('compliance_article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['compliance_article_id'], ['legislation_compliance_article.legislation_compliance_article_id'], ),
    sa.ForeignKeyConstraint(['legislation_act_section_id'], ['legislation_act_section.legislation_act_section_id'], ),
    sa.ForeignKeyConstraint(['order_stop_detail_id'], ['order_stop_detail.order_stop_detail_id'], ),
    sa.ForeignKeyConstraint(['parent_act_id'], ['legislation_act.legislation_act_id'], ),
    sa.PrimaryKeyConstraint('noncompliance_legislation_id')
    )
    op.create_table('noncompliance_permit',
    sa.Column('noncompliance_permit_id', sa.Integer(), nullable=False),
    sa.Column('order_stop_detail_id', sa.Integer(), nullable=True),
    sa.Column('section_number', sa.String(length=256), nullable=True),
    sa.Column('section_title', sa.String(length=2048), nullable=True),
    sa.Column('section_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_stop_detail_id'], ['order_stop_detail.order_stop_detail_id'], ),
    sa.PrimaryKeyConstraint('noncompliance_permit_id')
    )
    op.drop_table('legislation')
    op.add_column('inspection', sa.Column('inspection_report_sent_date', sa.DateTime(), nullable=True))
    op.add_column('inspection', sa.Column('inspection_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inspection', 'inspection_type', ['inspection_type_id'], ['inspection_type_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inspection', type_='foreignkey')
    op.drop_column('inspection', 'inspection_type_id')
    op.drop_column('inspection', 'inspection_report_sent_date')
    op.create_table('legislation',
    sa.Column('legislation_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_stop_detail_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('estimated_incident_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('noncompliant_description', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('parent_act_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('legislation_act_section_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('compliance_article_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['compliance_article_id'], ['legislation_compliance_article.legislation_compliance_article_id'], name='legislation_compliance_article_id_fkey'),
    sa.ForeignKeyConstraint(['legislation_act_section_id'], ['legislation_act_section.legislation_act_section_id'], name='legislation_legislation_act_section_id_fkey'),
    sa.ForeignKeyConstraint(['order_stop_detail_id'], ['order_stop_detail.order_stop_detail_id'], name='legislation_order_stop_detail_id_fkey'),
    sa.ForeignKeyConstraint(['parent_act_id'], ['legislation_act.legislation_act_id'], name='legislation_parent_act_id_fkey'),
    sa.PrimaryKeyConstraint('legislation_id', name='legislation_pkey')
    )
    op.drop_table('noncompliance_permit')
    op.drop_table('noncompliance_legislation')
    op.drop_table('inspection_type')
    # ### end Alembic commands ###
