"""empty message

Revision ID: fb359c2ed7cc
Revises: 43cd9db1c73a
Create Date: 2019-09-10 20:50:43.739346

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'fb359c2ed7cc'
down_revision = '43cd9db1c73a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspection', sa.Column('inspection_from_date', sa.DateTime(), nullable=True))
    op.add_column('inspection', sa.Column('inspection_to_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inspection', 'inspection_to_date')
    op.drop_column('inspection', 'inspection_from_date')
    # ### end Alembic commands ###
