version: "2"

services:
  ####################### NRIS_BACKEND Definition #######################
  nris_backend:
    restart: always
    container_name: nris_python
    build:
      context: backend
    ports:
      - 5500:5500
    volumes:
      - ./backend/:/app/
    depends_on:
      - postgres
    env_file: ./backend/.env
    networks:
      - nris

  ####################### NRIS_Postgres Definition #######################
  # Only for Local, openshift will share one db pod for all MDS services
  postgres:
    restart: always
    container_name: nris_postgres
    build:
      context: ../postgres
    environment:
      - POSTGRES_USER=nris
      - POSTGRES_PASSWORD=VsPJAuMJHu3IVMEv
      - POSTGRES_DB=mds
    ports:
      - "5432:5432"
    networks:
      - nris

####################### Networks Definition #######################
networks:
  nris:
    driver: "bridge"

####################### Volumes Definition #######################
volumes:
  postgres-data:
