# Only flyway latest supports ARM arch.
FROM flyway/flyway:latest

USER root

# apk replaced with apt. apk is only for alpine
RUN apt-get update && apt-get install -y gettext

COPY sql/* /flyway/sql/
COPY sql-prod/* /flyway/sql-prod/
COPY scripts/* /flyway/scripts/

ENTRYPOINT /flyway/scripts/run_migrations.sh
