from app.extensions import api
from flask_restplus import fields

CLIENT = api.model(
    'Client', {
        'clientid': fields.Integer,
        'type': fields.String,
        'org_legalname': fields.String,
        'org_doingbusinessas': fields.String,
        'ind_firstname': fields.String,
        'ind_lastname': fields.String,
        'ind_middlename': fields.String,
        'ind_phonenumber': fields.String,
        'dayphonenumber': fields.String,
        'dayphonenumberext': fields.String,
        'faxnumber': fields.String,
        'email': fields.String,
        'org_bcfedincorpnumber': fields.String,
        'org_bcregnumber': fields.String,
        'org_societynumber': fields.String,
        'org_hstregnumber': fields.String,
        'org_contactname': fields.String,
        'mailingaddressline1': fields.String,
        'mailingaddressline2': fields.String,
        'mailingaddresscity': fields.String,
        'mailingaddressprovstate': fields.String,
        'mailingaddresscountry': fields.String,
        'mailingaddresspostalzip': fields.String,
    })

CONTACT = api.model(
    'CONTACT', {
        'type': fields.String,
        'org_legalname': fields.String,
        'org_doingbusinessas': fields.String,
        'ind_firstname': fields.String,
        'ind_lastname': fields.String,
        'ind_middlename': fields.String,
        'ind_phonenumber': fields.String,
        'dayphonenumber': fields.String,
        'dayphonenumberext': fields.String,
        'faxnumber': fields.String,
        'email': fields.String,
        'org_bcfedincorpnumber': fields.String,
        'org_bcregnumber': fields.String,
        'org_societynumber': fields.String,
        'org_hstregnumber': fields.String,
        'org_contactname': fields.String,
        'mailingaddressline1': fields.String,
        'contacttype': fields.String,
        'contactcertificationtype': fields.String,
        'contactcertificationid': fields.String,
        'mailingaddressline2': fields.String,
        'mailingaddresscity': fields.String,
        'mailingaddressprovstate': fields.String,
        'mailingaddresscountry': fields.String,
        'mailingaddresspostalzip': fields.String,
        'seq_no': fields.Integer,
    })

DOCUMENT = api.model(
    'DOCUMENT', {
        'id': fields.Integer,
        'messageid': fields.Integer,
        'documenturl': fields.String,
        'filename': fields.String,
        'documenttype': fields.String,
        'description': fields.String,
        'document_manager_document_guid': fields.String,
        'is_final_package': fields.Boolean,
        'final_package_order': fields.Integer,
        'is_referral_package': fields.Boolean,
        'is_consultation_package': fields.Boolean
    })

PLACER_ACTIVITY = api.model(
    'PLACER_ACTIVITY', {
        'placeractivityid': fields.Integer,
        'type': fields.String,
        'quantity': fields.Integer,
        'depth': fields.Integer,
        'length': fields.Integer,
        'width': fields.Integer,
        'disturbedarea': fields.Arbitrary,
        'timbervolume': fields.Arbitrary,
    })

SETTLING_POND = api.model(
    'SETTLING_POND', {
        'settlingpondid': fields.String,
        'pondid': fields.String,
        'watersource': fields.String,
        'width': fields.Integer,
        'length': fields.Integer,
        'depth': fields.Integer,
        'constructionmethod': fields.String,
        'disturbedarea': fields.Arbitrary,
        'timbervolume': fields.Arbitrary,
    })

SURFACE_BULK_SAMPLE_ACTIVITY = api.model(
    'SURFACE_BULK_SAMPLE_ACTIVITY', {
        'type': fields.String,
        'quantity': fields.Integer,
        'disturbedarea': fields.Arbitrary,
        'timbervolume': fields.Arbitrary,
        'length': fields.Integer,
        'width': fields.Integer,
    })

SAND_GRAVEL_QUARRY_ACTIVITY = api.model(
    'SAND_GRAVEL_QUARRY_ACTIVITY', {
        'type': fields.String,
        'disturbedarea': fields.Arbitrary,
        'timbervolume': fields.Arbitrary,
        'length': fields.Integer,
        'width': fields.Integer,
    })

UNDER_EXP_NEW_ACTIVITY = api.model(
    'UNDER_EXP_NEW_ACTIVITY', {
        'type': fields.String,
        'incline': fields.Arbitrary,
        'inclineunits': fields.String,
        'quantity': fields.Integer,
        'length': fields.Arbitrary,
        'width': fields.Arbitrary,
        'height': fields.Arbitrary,
        'seq_no': fields.Integer,
    })

UNDER_EXP_REHAB_ACTIVITY = api.model(
    'UNDER_EXP_REHAB_ACTIVITY', {
        'type': fields.String,
        'incline': fields.Arbitrary,
        'inclineunits': fields.String,
        'quantity': fields.Integer,
        'length': fields.Arbitrary,
        'width': fields.Arbitrary,
        'height': fields.Arbitrary,
        'seq_no': fields.Integer,
    })

UNDER_EXP_SURFACE_ACTIVITY = api.model(
    'UNDER_EXP_SURFACE_ACTIVITY', {
        'type': fields.String,
        'quantity': fields.Integer,
        'disturbedarea': fields.Arbitrary,
        'timbervolume': fields.Arbitrary,
    })

EXP_ACCESS_ACTIVITY = api.model(
    'EXP_ACCESS_ACTIVITY', {
        'type': fields.String,
        'length': fields.Arbitrary,
        'lengthinmeters': fields.Integer,
        'width': fields.Integer,
        'disturbedarea': fields.Arbitrary,
        'timbervolume': fields.Arbitrary,
        'numberofsites': fields.Arbitrary,
    })

EXP_SURFACE_DRILL_ACTIVITY = api.model(
    'EXP_SURFACE_DRILL_ACTIVITY', {
        'type': fields.String,
        'numberofsites': fields.Arbitrary,
        'disturbedarea': fields.Arbitrary,
        'timbervolume': fields.Arbitrary,
        'length': fields.Integer,
        'width': fields.Integer,
    })

MECH_TRENCHING_ACTIVITY = api.model(
    'MECH_TRENCHING_ACTIVITY', {
        'type': fields.String,
        'numberofsites': fields.Integer,
        'disturbedarea': fields.Arbitrary,
        'timbervolume': fields.Arbitrary,
        'length': fields.Arbitrary,
        'width': fields.Arbitrary,
        'depth': fields.Arbitrary,
    })

WATER_SOURCE_ACTIVITY = api.model(
    'WATER_SOURCE_ACTIVITY', {
        'sourcewatersupply': fields.String,
        'type': fields.String,
        'useofwater': fields.String,
        'estimateratewater': fields.Arbitrary,
        'pumpsizeinwater': fields.Arbitrary,
        'locationwaterintake': fields.String,
        'seq_no': fields.Integer,
    })

EQUIPMENT = api.model('EQUIPMENT', {
    "type": fields.String,
    "size": fields.String,
    "quantity": fields.Integer
})

CAMP_ACTIVITY = api.model(
    'CAMP_ACTIVITY', {
        'name': fields.String,
        'peopleincamp': fields.Arbitrary,
        'numberofstructures': fields.Arbitrary,
        'wastedisposal': fields.String,
        'sanitaryfacilities': fields.String,
        'watersupply': fields.String,
        'quantityofwater': fields.Integer,
        'disturbedarea': fields.Arbitrary,
        'timbervolume': fields.Arbitrary,
        'length': fields.Integer,
        'width': fields.Integer,
    })

BUILDING_ACTIVITY = api.model(
    'BUILDING_ACTIVITY', {
        'name': fields.String,
        'purpose': fields.String,
        'structure': fields.String,
        'disturbedarea': fields.Arbitrary,
        'timbervolume': fields.Arbitrary,
        'length': fields.Integer,
        'width': fields.Integer,
    })

STAGING_AREA_ACTIVITY = api.model(
    'STAGING_AREA_ACTIVITY', {
        'name': fields.String,
        'disturbedarea': fields.Arbitrary,
        'timbervolume': fields.Arbitrary,
        'length': fields.Integer,
        'width': fields.Integer,
    })

APPLICATION = api.model(
    'Application', {
        'messageid': fields.Integer,
        'application_guid': fields.String,
        'now_application_guid': fields.String,
        'now_number': fields.String,
        'originating_system': fields.String,
        'mine_guid': fields.String,
        'mine_name': fields.String,
        'mine_region': fields.String,
        'trackingnumber': fields.Integer,
        'applicationtype': fields.String,
        'status': fields.String,
        'submitteddate': fields.DateTime,
        'receiveddate': fields.DateTime,
        'applicantclientid': fields.Integer,
        'submitterclientid': fields.Integer,
        'noticeofworktype': fields.String,
        'typeofpermit': fields.String,
        'typeofapplication': fields.String,
        'minenumber': fields.String,
        'minepurpose': fields.String,
        'latitude': fields.Fixed(decimals=7),
        'longitude': fields.Fixed(decimals=7),
        'gatelatitude': fields.Fixed(decimals=7),
        'gatelongitude': fields.Fixed(decimals=7),
        'nameofproperty': fields.String,
        'tenurenumbers': fields.String,
        'crowngrantlotnumbers': fields.String,
        'sitedirections': fields.String,
        'firstaidequipmentonsite': fields.String,
        'firstaidcertlevel': fields.String,
        'descexplorationprogram': fields.String,
        'describeexplosivetosite': fields.String,
        'proposedstartdate': fields.DateTime,
        'proposedenddate': fields.DateTime,
        'proposedstartmonth': fields.String,
        'proposedstartday': fields.String,
        'proposedendmonth': fields.String,
        'proposedendday': fields.String,
        'yearroundseasonal': fields.String,
        'landcommunitywatershed': fields.String,
        'landprivate': fields.String,
        'landlegaldesc': fields.String,
        'archsitesaffected': fields.String,
        'sandgravelquarryoperations': fields.String,
        'storeexplosivesonsite': fields.String,
        'bcexplosivespermitissued': fields.String,
        'bcexplosivespermitnumber': fields.String,
        'bcexplosivespermitexpiry': fields.DateTime,
        'campdisturbedarea': fields.Arbitrary,
        'camptimbervolume': fields.Arbitrary,
        'bldgdisturbedarea': fields.Arbitrary,
        'bldgtimbervolume': fields.Arbitrary,
        'stgedisturbedarea': fields.Arbitrary,
        'stgetimbervolume': fields.Arbitrary,
        'fuellubstoreonsite': fields.String,
        'fuellubstored': fields.Integer,
        'fuellubstoremethodbulk': fields.String,
        'fuellubstoremethodbarrel': fields.String,
        'cbsfreclamation': fields.String,
        'cbsfreclamationcost': fields.Arbitrary,
        'mechtrenchingreclamation': fields.String,
        'mechtrenchingreclamationcost': fields.Arbitrary,
        'expsurfacedrillreclamation': fields.String,
        'expsurfacedrillreclcorestorage': fields.String,
        'expsurfacedrillprogam': fields.String,
        'expsurfacedrillreclamationcost': fields.Arbitrary,
        'expaccessreclamation': fields.String,
        'expaccessreclamationcost': fields.Arbitrary,
        'surfacebulksampleprocmethods': fields.String,
        'surfacebulksamplereclamation': fields.String,
        'surfacebulksamplereclsephandl': fields.String,
        'surfacebulksamplerecldrainmiti': fields.String,
        'surfacebulksamplereclcost': fields.Arbitrary,
        'underexptotalore': fields.Integer,
        'underexptotaloreunits': fields.String,
        'underexptotalwaste': fields.Integer,
        'underexptotalwasteunits': fields.String,
        'underexpreclamation': fields.String,
        'underexpreclamationcost': fields.Arbitrary,
        'placerundergroundoperations': fields.String,
        'placerhandoperations': fields.String,
        'placerreclamationarea': fields.Arbitrary,
        'placerreclamation': fields.String,
        'placerreclamationcost': fields.Arbitrary,
        'sandgrvqrydepthoverburden': fields.Arbitrary,
        'sandgrvqrydepthtopsoil': fields.Arbitrary,
        'sandgrvqrystabilizemeasures': fields.String,
        'sandgrvqrywithinaglandres': fields.String,
        'sandgrvqryalrpermitnumber': fields.String,
        'sandgrvqrylocalgovsoilrembylaw': fields.String,
        'sandgrvqryofficialcommplan': fields.String,
        'sandgrvqrylandusezoning': fields.String,
        'sandgrvqryendlanduse': fields.String,
        'sandgrvqrytotalmineres': fields.Integer,
        'sandgrvqrytotalmineresunits': fields.String,
        'sandgrvqryannualextrest': fields.Integer,
        'sandgrvqryannualextrestunits': fields.String,
        'sandgrvqryreclamation': fields.String,
        'sandgrvqryreclamationbackfill': fields.String,
        'sandgrvqryreclamationcost': fields.Arbitrary,
        'sandgrvqrygrdwtravgdepth': fields.Arbitrary,
        'sandgrvqrygrdwtrexistingareas': fields.String,
        'sandgrvqrygrdwtrtestpits': fields.String,
        'sandgrvqrygrdwtrtestwells': fields.String,
        'sandgrvqrygrdwtrother': fields.String,
        'sandgrvqrygrdwtrmeasprotect': fields.String,
        'sandgrvqryimpactdistres': fields.Integer,
        'sandgrvqryimpactdistwater': fields.Integer,
        'sandgrvqryimpactnoise': fields.String,
        'sandgrvqryimpactprvtaccess': fields.String,
        'sandgrvqryimpactprevtdust': fields.String,
        'sandgrvqryimpactminvisual': fields.String,
        'cutlinesexplgridtotallinekms': fields.Integer,
        'cutlinesexplgridtimbervolume': fields.Arbitrary,
        'cutlinesreclamation': fields.String,
        'cutlinesreclamationcost': fields.Arbitrary,
        'pondswastewatertreatfacility': fields.String,
        'freeusepermit': fields.String,
        'licencetocut': fields.String,
        'timbertotalvolume': fields.Arbitrary,
        'campbuildstgetotaldistarea': fields.Arbitrary,
        'mechtrenchingtotaldistarea': fields.Arbitrary,
        'expsurfacedrilltotaldistarea': fields.Arbitrary,
        'expaccesstotaldistarea': fields.Arbitrary,
        'surfacebulksampletotaldistarea': fields.Arbitrary,
        'placertotaldistarea': fields.Arbitrary,
        'underexptotaldistarea': fields.Arbitrary,
        'sandgrvqrytotaldistarea': fields.Arbitrary,
        'pondstotaldistarea': fields.Arbitrary,
        'reclcostsubtotal': fields.Arbitrary,
        'reclcostexist': fields.Arbitrary,
        'reclcostrecl': fields.Arbitrary,
        'reclcosttotal': fields.Arbitrary,
        'reclareasubtotal': fields.Arbitrary,
        'reclareaexist': fields.Arbitrary,
        'reclarearecl': fields.Arbitrary,
        'reclareatotal': fields.Arbitrary,
        'anyotherinformation': fields.String,
        'vfcbcapplicationurl': fields.String,
        'messagecreateddate': fields.DateTime,
        'processed': fields.String,
        'processeddate': fields.DateTime,
        'cutlinesexplgriddisturbedarea': fields.Arbitrary,
        'pondsrecycled': fields.String,
        'pondsexfiltratedtoground': fields.String,
        'pondsdischargedtoenv': fields.String,
        'pondsreclamation': fields.String,
        'pondsreclamationcost': fields.Arbitrary,
        'sandgrvqrytotalexistdistarea': fields.Arbitrary,
        'nrsosapplicationid': fields.String,
        'isblastselect': fields.String,
        'istimberselect': fields.String,
        'applicantindividualorcompany': fields.String,
        'applicantrelationship': fields.String,
        'termofapplication': fields.Arbitrary,
        'hasaccessauthorizations': fields.String,
        'accessauthorizationsdetails': fields.String,
        'accessauthorizationskeyprovided': fields.String,
        'landpresentcondition': fields.String,
        'currentmeansofaccess': fields.String,
        'physiography': fields.String,
        'oldequipment': fields.String,
        'typeofvegetation': fields.String,
        'recreationuse': fields.String,
        'isparkactivities': fields.String,
        'hasltgovauthorization': fields.String,
        'hasarchaeologicalprotectionplan': fields.String,
        'isonprivateland': fields.String,
        'hasengagedfirstnations': fields.String,
        'hasculturalheritageresources': fields.String,
        'archaeologicalprotectionplan': fields.String,
        'firstnationsactivities': fields.String,
        'curturalheritageresources': fields.String,
        'hasproposedcrossings': fields.String,
        'proposedcrossingschanges': fields.String,
        'cleanoutdisposalplan': fields.String,
        'maxannualtonnage': fields.Arbitrary,
        'maxannualcubicmeters': fields.Arbitrary,
        'proposedproduction': fields.Arbitrary,
        'isaccessgated': fields.String,
        'permitnumber': fields.String,
        'atsauthorizationnumber': fields.Arbitrary,
        'atsprojectnumber': fields.Arbitrary,
        'filenumberofappl': fields.String,
        'originalstartdate': fields.DateTime,
        'annualsummarysubmitted': fields.String,
        'firstyearofmulti': fields.String,
        'authorizationdetail': fields.String,
        'oncrownland': fields.String,
        'havelicenceofoccupation': fields.String,
        'appliedforlicenceofoccupation': fields.String,
        'licenceofoccupation': fields.String,
        'noticeservedtoprivate': fields.String,
        'sandgrvqryprogressivereclam': fields.String,
        'sandgrvqrymaxunreclaimed': fields.Arbitrary,
        'pondtypeofsediment': fields.String,
        'pondtypeconstruction': fields.String,
        'pondarea': fields.String,
        'pondspillwaydesign': fields.String,
        'camphealthauthority': fields.String,
        'camphealthconsent': fields.String,
        'proposedproductionunit': fields.String,
        'placerstreamdiversion': fields.String,
        'sandgrvqrydescription': fields.String,
        'hassurfacedisturbanceoutsidetenure': fields.String,
        'bedrockexcavation': fields.String,
        'proposedactivites': fields.String,
        'applicant': fields.Nested(CLIENT),
        'submitter': fields.Nested(CLIENT),
        'documents': fields.List(fields.Nested(DOCUMENT)),
        'contacts': fields.List(fields.Nested(CONTACT)),
        'existing_placer_activity': fields.Nested(PLACER_ACTIVITY),
        'existing_settling_pond': fields.Nested(SETTLING_POND),
        'exp_access_activity': fields.List(fields.Nested(EXP_ACCESS_ACTIVITY)),
        'exp_surface_drill_activity': fields.List(fields.Nested(EXP_SURFACE_DRILL_ACTIVITY)),
        'proposed_placer_activity': fields.Nested(PLACER_ACTIVITY),
        'proposed_settling_pond': fields.Nested(SETTLING_POND),
        'surface_bulk_sample_activity': fields.List(fields.Nested(SURFACE_BULK_SAMPLE_ACTIVITY)),
        'sand_grv_qry_activity': fields.List(fields.Nested(SAND_GRAVEL_QUARRY_ACTIVITY)),
        'under_exp_new_activity': fields.List(fields.Nested(UNDER_EXP_NEW_ACTIVITY)),
        'under_exp_rehab_activity': fields.List(fields.Nested(UNDER_EXP_REHAB_ACTIVITY)),
        'under_exp_surface_activity': fields.List(fields.Nested(UNDER_EXP_SURFACE_ACTIVITY)),
        'water_source_activity': fields.List(fields.Nested(WATER_SOURCE_ACTIVITY)),
        'mech_trenching_activity': fields.List(fields.Nested(MECH_TRENCHING_ACTIVITY)),
        'camps': fields.List(fields.Nested(CAMP_ACTIVITY)),
        'buildings': fields.List(fields.Nested(BUILDING_ACTIVITY)),
        'stagingareas': fields.List(fields.Nested(STAGING_AREA_ACTIVITY)),
        'equipment': fields.List(fields.Nested(EQUIPMENT))
    })

APPLICATION_LIST = api.model(
    'ApplicationList', {
        'application_guid': fields.String,
        'now_application_guid': fields.String,
        'mine_guid': fields.String,
        'mine_name': fields.String,
        'mine_region': fields.String,
        'minenumber': fields.String,
        'noticeofworktype': fields.String,
        'trackingnumber': fields.Integer,
        'status': fields.String,
        'receiveddate': fields.Date,
    })

PAGINATED_LIST = api.model(
    'List', {
        'current_page': fields.Integer,
        'total_pages': fields.Integer,
        'items_per_page': fields.Integer,
        'total': fields.Integer,
    })

PAGINATED_APPLICATION_LIST = api.inherit('PaginatedApplicationList', PAGINATED_LIST, {
    'records': fields.List(fields.Nested(APPLICATION_LIST)),
})

APPLICATIONNDA = api.model(
    'ApplicationNDA', {
        'messageid': fields.Integer,
        'application_nda_guid': fields.String,
        'originating_system': fields.String,
        'mine_guid': fields.String,
        'trackingnumber': fields.Integer,
        'applicationtype': fields.String,
        'status': fields.String,
        'submitteddate': fields.DateTime,
        'receiveddate': fields.DateTime,
        'typedeemedauthorization': fields.String,
        'permitnumber': fields.String,
        'minenumber': fields.String,
        'nownumber': fields.String,
        'planactivitiesdrillprogram': fields.String,
        'planactivitiesipsurvey': fields.String,
        'proposedstartdate': fields.DateTime,
        'proposedenddate': fields.DateTime,
        'totallinekilometers': fields.Integer,
        'descplannedactivities': fields.String,
        'proposednewenddate': fields.DateTime,
        'reasonforextension': fields.String,
        'anyotherinformation': fields.String,
        'vfcbcapplicationurl': fields.String,
        'messagecreateddate': fields.DateTime,
        'processed': fields.String,
        'processeddate': fields.DateTime,
        'nrsosapplicationid': fields.String,
        'applicant': fields.Nested(CLIENT),
        'submitter': fields.Nested(CLIENT),
        'documents': fields.List(fields.Nested(DOCUMENT))
    })

APPLICATIONSTARTSTOP = api.model(
    'ApplicationStartStop', {
        'termOfPermit': fields.String,
        'permitIssuedDate': fields.String,
        'portalApplicationPackageId': fields.String,
        'nowNumber': fields.String,
        'applicationId': fields.String,
        'permitExpiryDate': fields.String,
        'noticeOfWorkType': fields.String,
        'applicationType': fields.String,
        'processedDate': fields.String,
        'contacts': fields.List(fields.Nested(CLIENT)),
        'mineNumber': fields.String,
        'typeOfApplication': fields.String,
        'applicationDescription': fields.String,
        'attachments': fields.List(fields.Nested(DOCUMENT)),
        'status': fields.String,
        'approvalNumber': fields.String,
        'links': fields.List(fields.String),
        'stopWorkDate': fields.String,
        'startWorkDate': fields.String,
        'receivedDate': fields.String,
        'portalApplicationPackageNumber': fields.String,
        'typeOfPermit': fields.String,
        'proposedStartDate': fields.String,
        'otherInformation': fields.String,
        'permitStartDate': fields.String,
        'submittedDate': fields.String,
        'portalApplicationId': fields.String,
        'proposedEndDate': fields.String
    })