#!/usr/bin/env python

import sys

# Read stdin input data from the TUS daemon
data = ''.join(sys.stdin.readlines())

# Test if data is valid JSON... just to be sure...
# And we need some data from the JSON as well
try:
    upload_data = json.loads(data)
except Exception as ex:
    print(ex)
    # Send exit code higher then 0 to stop the upload process on the Tus server
    sys.exit(1)

filename = upload_data['Upload']['MetaData'].get('filename', None)
key = upload_data['Upload']['Storage'].get('Key', None)
