FROM tusproject/tusd:v1.3.0

COPY init.sh .
COPY ./hooks/post-finish ./hooks/

USER root

RUN chmod +x ./hooks/post-finish

RUN apk add --no-cache curl \
    && apk add --no-cache python3 \
    && pip3 install --upgrade pip \
    && pip3 install awscli \
    && apk add --no-cache jq \
    && chmod +x ./hooks/post-finish

WORKDIR /srv/tusd-data

USER 1000

ENTRYPOINT [ "./init.sh" ]