apiVersion: apps/v1
kind: Deployment
metadata:
  name: tusd
spec:
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - tusd
        from:
          kind: ImageStreamTag
          name: tusd:prod
          namespace: 4c2ba9-tools
  template:
    spec:
      containers:
        - name: tusd
          image: "image-registry.openshift-image-registry.svc:5000/4c2ba9-tools/tusd:prod"
          env:
            - name: S3_PREFIX
              value: mds-files-prod/
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 30m
              memory: 96Mi
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: IfNotPresent
          capabilities: {}
      restartPolicy: Always
      dnsPolicy: ClusterFirst