---
kind: Template
apiVersion: v1
metadata:
  name: prometheus
  creationTimestamp: 
parameters:
- name: NAME
  displayName: Name
  description: A name used for all objects
  required: true
  value: prometheus
- name: APP_NAME
  displayName: App Name
  description: Used to group components together in the OpenShift console.
  required: true
  value: monitoring
- name: OUTPUT_IMAGE_TAG
  displayName: Output Image Tag
  description: The tag given to the built image.
  required: true
  value: v2.19.2
- name: SOURCE_IMAGE_KIND
  displayName: Source Image Kind
  description: The 'kind' (type) of the  source image; typically ImageStreamTag, or
    DockerImage.
  required: true
  value: DockerImage
- name: SOURCE_IMAGE_NAME
  displayName: Source Image Name
  description: The name of the source image.
  required: true
  value: prom/prometheus
- name: SOURCE_IMAGE_TAG
  displayName: Source Image Tag
  description: The tag of the source image.
  required: true
  value: v2.19.2
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${NAME}"
    labels:
      shared: 'true'
      app: "${APP_NAME}"
    annotations: {}
  spec:
    lookupPolicy:
      local: false
    tags:
    - name: "${OUTPUT_IMAGE_TAG}"
      annotations: 
      from:
        kind: "${SOURCE_IMAGE_KIND}"
        name: "${SOURCE_IMAGE_NAME}:${SOURCE_IMAGE_TAG}"
      generation: 1
      importPolicy: {}
      referencePolicy:
        type: Local
