export const AUTHENTICATION = "AUTHENTICATION";

// User Dashboard Info
export const USER_MINE_INFO = "USER_MINE_INFO";
export const GET_USER_MINE_INFO = "GET_USER_MINE_INFO";
export const GET_MINE_RECORD = "GET_MINE_RECORD";

export const MODAL = "MODAL";

export const STATIC_CONTENT = "STATIC_CONTENT";

export const GET_EXPECTED_DOCUMENT_STATUS = "GET_EXPECTED_DOCUMENT_STATUS";
export const GET_MINE_DOCUMENTS = "GET_MINE_DOCUMENTS";
export const ADD_MINE_DOCUMENT_TO_EXPECTED_DOCUMENT = "ADD_MINE_DOCUMENT_TO_EXPECTED_DOCUMENT";
export const UPDATE_EXPECTED_DOCUMENT = "UPDATE_EXPECTED_DOCUMENT";
export const REMOVE_MINE_EXPECTED_DOCUMENT = "REMOVE_MINE_EXPECTED_DOCUMENT";
