export const AUTHENTICATION = "AUTHENTICATION";
export const UNAUTHENTICATE_USER = "UNAUTHENTICATE_USER";
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const GET_USER_INFO = "GET_USER_INFO";

// User Dashboard Info
export const USER_MINE_INFO = "USER_MINE_INFO";
export const GET_USER_MINE_INFO = "GET_USER_MINE_INFO";
export const GET_MINE_RECORD = "GET_MINE_RECORD";

export const MODAL = "MODAL";

export const STATIC_CONTENT = "STATIC_CONTENT";

export const GET_MINE_DOCUMENTS = "GET_MINE_DOCUMENTS";
export const ADD_DOCUMENT_TO_EXPECTED_DOCUMENT = "ADD_DOCUMENT_TO_EXPECTED_DOCUMENT";
export const UPDATE_EXPECTED_DOCUMENT = "UPDATE_EXPECTED_DOCUMENT";
export const REMOVE_MINE_EXPECTED_DOCUMENT = "REMOVE_MINE_EXPECTED_DOCUMENT";
