---
## Default Logstash configuration from logstash-docker.
## from https://github.com/elastic/logstash-docker/blob/master/build/logstash/config/logstash-oss.yml
#
http.host: "0.0.0.0"
path.config: /usr/share/logstash/pipeline
log.level: debug
cloud.id: "${ELASTIC_CLOUD_ID}"
cloud.auth: "${ELASTIC_CLOUD_AUTH}"
xpack.monitoring.enabled: false
xpack.management.enabled: false
xpack.monitoring.elasticsearch.hosts: "${ELASTIC_HOST}"
