// Reducers
import complianceReducerObject from "./reducers/complianceReducer";
import authenticationReducerObject from "./reducers/authenticationReducer";
import incidentReducerObject from "./reducers/incidentReducer";
import mineReducerObject from "./reducers/mineReducer";
import minespaceReducerObject from "./reducers/minespaceReducer";
import modalReducerObject from "./reducers/modalReducer";
import noticeOfWorkReducerObject from "./reducers/noticeOfWorkReducer";
import partiesReducerObject from "./reducers/partiesReducer";
import permitReducerObject from "./reducers/permitReducer";
import reportReducerObject from "./reducers/reportReducer";
import searchReducerObject from "./reducers/searchReducer";
import staticContentReducerObject from "./reducers/staticContentReducer";
import userReducerObject from "./reducers/userReducer";
import varianceReducerObject from "./reducers/varianceReducer";
import securitiesReducerObject from "./reducers/securitiesReducer";
import orgbookReducerObject from "./reducers/orgbookReducer";

export const complianceReducer = complianceReducerObject;
export const authenticationReducer = authenticationReducerObject;
export const incidentReducer = incidentReducerObject;
export const mineReducer = mineReducerObject;
export const minespaceReducer = minespaceReducerObject;
export const modalReducer = modalReducerObject;
export const noticeOfWorkReducer = noticeOfWorkReducerObject;
export const partiesReducer = partiesReducerObject;
export const permitReducer = permitReducerObject;
export const reportReducer = reportReducerObject;
export const searchReducer = searchReducerObject;
export const staticContentReducer = staticContentReducerObject;
export const userReducer = userReducerObject;
export const varianceReducer = varianceReducerObject;
export const securitiesReducer = securitiesReducerObject;
export const orgbookReducer = orgbookReducerObject;
