CREATE EXTENSION IF NOT EXISTS pg_trgm;

DO $$
BEGIN
CREATE ROLE postgres WITH LOGIN SUPERUSER;
EXCEPTION WHEN duplicate_object THEN RAISE NOTICE '%, skipping', SQLERRM USING ERRCODE = SQLSTATE;
END
$$;
