FROM postgis/postgis:16-3.4

RUN sed -i 's/$/ 13/' /etc/apt/sources.list.d/pgdg.list

RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
    postgresql-13 \
    postgresql-13-postgis-3 \
    ; \
    rm -rf /var/lib/apt/lists/*

ENV PGBINOLD /usr/lib/postgresql/13/bin
ENV PGBINNEW /usr/lib/postgresql/16/bin

ENV PGDATAOLD /var/lib/postgresql/13/data
ENV PGDATANEW /var/lib/postgresql/16/data

RUN set -eux; \
    mkdir -p "$PGDATAOLD" "$PGDATANEW"; \
    chown -R postgres:postgres /var/lib/postgresql

WORKDIR /var/lib/postgresql

COPY docker-upgrade.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-upgrade.sh

ENTRYPOINT ["/usr/local/bin/docker-upgrade.sh"]

CMD ["pg_upgrade"]