export const REQUEST = 'REQUEST';
export const SUCCESS = 'SUCCESS';
export const ERROR = 'ERROR';

export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const STORE_KEYCLOAK_DATA = 'STORE_KEYCLOAK_DATA';
export const STORE_USER_ACCESS_DATA = 'STORE_USER_ACCESS_DATA';
export const LOGOUT = 'LOGOUT';

export const ADD_MINE_RECORD = 'ADD_MINE';
export const UPDATE_MINE_RECORD = 'UPDATE_MINE_RECORD';
export const STORE_MINE_RECORDS = 'STORE_MINE_RECORDS';
export const STORE_MINE_RECORD = 'STORE_MINE_RECORD';

export const ADD_PERSONNEL = 'ADD_PERSONNEL';
export const STORE_PERSONNEL = 'STORE_PERSONNEL';
export const STORE_PERSONNEL_LIST ='STORE_PERSONNEL_LIST';

