// Redux Actions
export const REQUEST = "REQUEST";
export const SUCCESS = "SUCCESS";
export const ERROR = "ERROR";
export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const STORE_KEYCLOAK_DATA = "STORE_KEYCLOAK_DATA";
export const STORE_USER_ACCESS_DATA = "STORE_USER_ACCESS_DATA";
export const LOGOUT = "LOGOUT";

export const UPDATE_MINE_RECORD = "UPDATE_MINE_RECORD";
export const STORE_MINE_LIST = "STORE_MINE_LIST";
export const STORE_MINE = "STORE_MINE";
export const STORE_MINE_NAME_LIST = "STORE_MINE_NAME_LIST";
export const STORE_STATUS_OPTIONS = "STORE_STATUS_OPTIONS";
export const STORE_REGION_OPTIONS = "STORE_REGION_OPTIONS";

export const STORE_PARTY = "STORE_PARTY";
export const STORE_PARTIES = "STORE_PARTIES";

export const STORE_DOCUMENT_STATUS_OPTIONS = "STORE_DOCUMENT_STATUS_OPTIONS";
