// Redux Forms
export const UPDATE_MINE_MANAGER = 'UPDATE_MINE_MANAGER';
export const ADD_PARTY = 'ADD_PARTY';
export const ADD_PERMITTEE = 'ADD_PERMITTEE';
export const ADD_TENURE_NUMBER = 'ADD_TENURE_NUMBER';
export const MINE_RECORD = 'MINE_RECORD';
export const SEARCH_COORDINATES = 'SEARCH_COORDINATES';
export const UPDATE_PERMITTEE = 'UPDATE_PERMITTEE';