// Redux Forms
export const ADD_FULL_PARTY = "ADD_FULL_PARTY";
export const ADD_QUICK_PARTY = "ADD_QUICK_PARTY";
export const ADD_TENURE_NUMBER = "ADD_TENURE_NUMBER";
export const MINE_RECORD = "MINE_RECORD";
export const SEARCH_COORDINATES = "SEARCH_COORDINATES";
export const UPDATE_PERMITTEE = "UPDATE_PERMITTEE";
export const ADD_TAILINGS = "ADD_TAILINGS";
export const ADD_TAILINGS_REPORT = "ADD_TAILINGS_REPORT";
export const EDIT_TAILINGS = "EDIT_TAILINGS";
export const ADD_PARTY_RELATIONSHIP = "ADD_PARTY_RELATIONSHIP";
export const EDIT_PARTY_RELATIONSHIP = "EDIT_PARTY_RELATIONSHIP";
export const ADVANCE_SEARCH = "ADVANCE_SEARCH";
export const ADD_MINESPACE_USER = "ADD_MINESPACE_USER";
