// Redux reducers
export const CREATE_MINE_RECORD = "CREATE_MINE_RECORD";
export const GET_MINE_RECORDS = "GET_MINE_RECORDS";
export const GET_MINE_RECORD = "GET_MINE_RECORD";
export const GET_MINE_NAME_LIST = "GET_MINE_NAME_LIST";
export const GET_STATUS_OPTIONS = "GET_STATUS_OPTIONS";
export const GET_REGION_OPTIONS = "GET_REGION_OPTIONS";
export const UPDATE_MINE_RECORD = "UPDATE_MINE_RECORD";
export const CREATE_TSF = "CREATE_TSF";
export const EDIT_TSF_REPORT = "EDIT_TSF_REPORT";
export const ADD_MINE_EXPECTED_DOCUMENT = "ADD_MINE_EXPECTED_DOCUMENT";
export const REMOVE_EXPECTED_DOCUMENT = "REMOVE_EXPECTED_DOCUMENT";
export const MINES = "MINES";
export const GET_EXPECTED_DOCUMENT_STATUS = "GET_EXPECTED_DOCUMENT_STATUS";
export const UPDATE_EXPECTED_DOCUMENT = "UPDATE_EXPECTED_DOCUMENT";
export const GET_MINE_TSF_REQUIRED_REPORTS = "GET_MINE_TSF_REQUIRED_REPORTS";
export const GET_TENURE_TYPES = "GET_TENURE_TYPES";

export const AUTHENTICATION = "AUTHENTICATION";

export const CREATE_PARTY = "CREATE_PARTY";
export const PARTIES = "PARTIES";
export const GET_PARTIES = "GET_PARTIES";
export const GET_PARTY = "GET_PARTY";

export const ADD_MINE_MANAGER = "ADD_MINE_MANAGER";
export const ADD_PERMITTEE = "ADD_PERMITTEE";

export const MODAL = "MODAL";
export const GET_PARTY_RELATIONSHIP_TYPES = "GET_PARTY_RELATIONSHIP_TYPES";
export const ADD_PARTY_RELATIONSHIP = "ADD_PARTY_RELATIONSHIP";
export const FETCH_PARTY_RELATIONSHIPS = "FETCH_PARTY_RELATIONSHIPS";
export const REMOVE_PARTY_RELATIONSHIP = "REMOVE_PARTY_RELATIONSHIP";
export const UPDATE_PARTY_RELATIONSHIP = "UPDATE_PARTY_RELATIONSHIP";
