export const CREATE_MINE_RECORD = 'CREATE_MINE_RECORD';
export const GET_MINE_RECORDS = 'GET_MINE_RECORDS';
export const GET_MINE_RECORD = 'GET_MINE_RECORD';
export const UPDATE_MINE_RECORD = 'UPDATE_MINE_RECORD';
export const MINES = 'MINES';

export const AUTHENTICATION = 'AUTHENTICATION';