// Redux reducers
export const CREATE_MINE_RECORD = 'CREATE_MINE_RECORD';
export const GET_MINE_RECORDS = 'GET_MINE_RECORDS';
export const GET_MINE_RECORD = 'GET_MINE_RECORD';
export const GET_MINE_NAME_LIST = 'GET_MINE_NAME_LIST';
export const GET_STATUS_OPTIONS = 'GET_STATUS_OPTIONS';
export const GET_REGION_OPTIONS = 'GET_REGION_OPTIONS';
export const UPDATE_MINE_RECORD = 'UPDATE_MINE_RECORD';
export const CREATE_TSF = 'CREATE_TSF';
export const EDIT_TSF_REPORT = 'EDIT_TSF_REPORT';
export const REMOVE_EXPECTED_DOCUMENT = 'REMOVE_EXPECTED_DOCUMENT';
export const MINES = 'MINES';

export const AUTHENTICATION = 'AUTHENTICATION';

export const CREATE_PARTY = 'CREATE_PARTY';
export const PARTIES = 'PARTIES';
export const GET_PARTIES = 'GET_PARTIES';
export const GET_PARTY = 'GET_PARTY';

export const ADD_MINE_MANAGER = 'ADD_MINE_MANAGER';
export const ADD_PERMITTEE = 'ADD_PERMITTEE'

export const MODAL= 'MODAL';
