"""empty message

Revision ID: cd58c2871e42
Revises: 
Create Date: 2019-04-24 23:30:12.818407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd58c2871e42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factorial_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_val', sa.Integer(), nullable=False),
    sa.Column('output_val', sa.Integer(), nullable=False),
    sa.Column('exec_timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('input_val')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('factorial_record')
    # ### end Alembic commands ###
