apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend
  labels:
    name: backend
spec:
  maxReplicas: 4
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  targetCPUUtilizationPercentage: 95