apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes and load balances the application pods
  creationTimestamp: null
  labels:
    app: tusd
    app.kubernetes.io/component: documents
    app.kubernetes.io/instance: tusd
    app.kubernetes.io/managed-by: template
    app.kubernetes.io/name: tusd
    app.kubernetes.io/part-of: Core
    cluster-name: tusd
    phase: deploy
  name: tusd

spec:
  ports:
    - port: 1080
      protocol: TCP
      targetPort: 1080
  selector:
    app.kubernetes.io/name: tusd
  type: ClusterIP
  sessionAffinity: None
