// Reducers
import activityReducerObject from "./reducers/activityReducer";
import complianceReducerObject from "./reducers/complianceReducer";
import authenticationReducerObject from "./reducers/authenticationReducer";
import incidentReducerObject from "./reducers/incidentReducer";
import workInformationReducerObject from "./reducers/workInformationReducer";
import mineReducerObject from "./reducers/mineReducer";
import minespaceReducerObject from "./reducers/minespaceReducer";
import modalReducerObject from "./reducers/modalReducer";
import documentViewerReducerObject from "./reducers/documentViewerReducer";
import noticeOfWorkReducerObject from "./reducers/noticeOfWorkReducer";
import partiesReducerObject from "./reducers/partiesReducer";
import permitReducerObject from "./reducers/permitReducer";
import reportReducerObject from "./reducers/reportReducer";
import searchReducerObject from "./reducers/searchReducer";
import staticContentReducerObject from "./reducers/staticContentReducer";
import userReducerObject from "./reducers/userReducer";
import varianceReducerObject from "./reducers/varianceReducer";
import securitiesReducerObject from "./reducers/securitiesReducer";
import orgbookReducerObject from "./reducers/orgbookReducer";
import explosivesPermitReducerObject from "./reducers/explosivesPermitReducer";
import externalAuthorizationReducerObject from "./reducers/externalAuthorizationReducer";
import projectReducerObject from "./reducers/projectReducer";
import noticeOfDepartureReducerObject from "./reducers/noticeOfDepartureReducer";

export const activityReducer = activityReducerObject;
export const complianceReducer = complianceReducerObject;
export const authenticationReducer = authenticationReducerObject;
export const incidentReducer = incidentReducerObject;
export const workInformationReducer = workInformationReducerObject;
export const mineReducer = mineReducerObject;
export const minespaceReducer = minespaceReducerObject;
export const modalReducer = modalReducerObject;
export const documentViewerReducer = documentViewerReducerObject;
export const noticeOfWorkReducer = noticeOfWorkReducerObject;
export const partiesReducer = partiesReducerObject;
export const permitReducer = permitReducerObject;
export const reportReducer = reportReducerObject;
export const searchReducer = searchReducerObject;
export const staticContentReducer = staticContentReducerObject;
export const userReducer = userReducerObject;
export const varianceReducer = varianceReducerObject;
export const securitiesReducer = securitiesReducerObject;
export const orgbookReducer = orgbookReducerObject;
export const explosivesPermitReducer = explosivesPermitReducerObject;
export const externalAuthorizationReducer = externalAuthorizationReducerObject;
export const projectReducer = projectReducerObject;
export const noticeOfDepartureReducer = noticeOfDepartureReducerObject;
