GRANT ALL PRIVILEGES ON DATABASE mds TO mds;
GRANT ALL PRIVILEGES ON SCHEMA public TO mds;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO mds;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO mds;

GRANT ALL PRIVILEGES ON SCHEMA nris TO nris;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA nris TO nris;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA nris TO nris;