-- Grant all table permissions to the non super-user
GRANT ALL PRIVILEGES ON DATABASE mds TO mds;
GRANT ALL PRIVILEGES ON SCHEMA public TO mds;
GRANT ALL PRIVILEGES ON ALL TABLES TO mds;
GRANT ALL PRIVILEGES ON ALL SEQUENCES TO mds;