-- Grant permissions to the non-superuser

GRANT ALL PRIVILEGES ON DATABASE mds TO mds;
GRANT ALL PRIVILEGES ON SCHEMA mds.public TO mds;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA mds.public TO mds;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA mds.public TO mds;

GRANT ALL PRIVILEGES ON DATABASE mds TO mds;
GRANT ALL PRIVILEGES ON SCHEMA mds_test.public TO mds;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA mds_test.public TO mds;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA mds_test.public TO mds;