ALTER TABLE variance
ADD COLUMN variance_no integer;

ALTER TABLE variance ADD CONSTRAINT unique_variance_no_idx UNIQUE (variance_no);

COMMENT ON COLUMN variance.variance_no IS 'A human-readable, unique identifier for a variance, generated by MDS.';

CREATE SEQUENCE variance_no_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE variance_no_seq OWNER TO mds;
ALTER SEQUENCE variance_no_seq OWNED BY variance.variance_no;

UPDATE variance
SET variance_no = nextval('variance_no_seq')
WHERE variance_id IN (
    SELECT variance_id
    FROM variance
    -- All historical variances were added before June 26th
    WHERE create_timestamp >= '2019-06-26'::date
    ORDER BY create_timestamp ASC
)
AND variance_no IS NULL;

ALTER TABLE ONLY variance ALTER COLUMN variance_no SET DEFAULT nextval('variance_no_seq'::regclass);
