CREATE SCHEMA IF NOT EXISTS now;

-- Create NRIS User if it doesn't exist
DO
$$
BEGIN
    IF NOT EXISTS(select from pg_catalog.pg_roles where rolname= 'now') THEN
        CREATE USER now with PASSWORD '$NRIS_USER_PASSWORD';
    END IF;
END
$$;

CREATE TABLE now.client (
    CLIENTID NUMBER(9,0) PRIMARY KEY,
    "TYPE" character varying(30),
    ORG_LEGALNAME character varying(250),
    ORG_DOINGBUSINESSAS character varying(150),
    IND_FIRSTNAME character varying(60),
    IND_LASTNAME character varying(60),
    IND_MIDDLENAME character varying(60),
    IND_PHONENUMBER character varying(10),
    DAYPHONENUMBER character varying(10),
    DAYPHONENUMBEREXT character varying(4),
    FAXNUMBER character varying(10),
    EMAIL character varying(60),
    ORG_BCFEDINCORPNUMBER character varying(30),
    ORG_BCREGNUMBER character varying(10),
    ORG_SOCIETYNUMBER character varying(30),
    ORG_HSTREGNUMBER character varying(30),
    ORG_CONTACTNAME character varying(4000),
    MAILINGADDRESSLINE1 character varying(4000),
    MAILINGADDRESSLINE2 character varying(60),
    MAILINGADDRESSCITY character varying(100),
    MAILINGADDRESSPROVSTATE character varying(200),
    MAILINGADDRESSCOUNTRY character varying(50),
    MAILINGADDRESSPOSTALZIP character varying(10)
);

CREATE TABLE now.application_nda (
    MESSAGEID numeric(9,0) PRIMARY KEY,
    TRACKINGNUMBER numeric(9,0),
    APPLICATIONTYPE character varying(100),
    STATUS character varying(60),
    SUBMITTEDDATE date,
    RECEIVEDDATE date,
    APPLICANTCLIENTID numeric(9,0),
    SUBMITTERCLIENTID numeric(9,0),
    TYPEDEEMEDAUTHORIZATION character varying(50),
    PERMITNUMBER character varying(50),
    MINENUMBER character varying(50),
    NOWNUMBER character varying(50),
    PLANACTIVITIESDRILLPROGRAM character varying(3),
    PLANACTIVITIESIPSURVEY character varying(3),
    PROPOSEDSTARTDATE date,
    PROPOSEDENDDATE date,
    TOTALLINEKILOMETERS NUMBER,
    DESCPLANNEDACTIVITIES character varying(4000),
    PROPOSEDNEWENDDATE DATE,
    REASONFOREXTENSION character varying(4000),
    ANYOTHERINFORMATION character varying(4000),
    VFCBCAPPLICATIONURL character varying(4000),
    MESSAGECREATEDDATE date,
    PROCESSED character varying(1) DEFAULT 'N' ,
    PROCESSEDDATE date,
    NRSOSAPPLICATIONID character varying(50),

    FOREIGN KEY (APPLICANTCLIENTID) REFERENCES now.client(CLIENTID) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY (SUBMITTERCLIENTID) REFERENCES now.client(CLIENTID) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE now.application_start_stop (
    MESSAGEID numeric(9,0) PRIMARY KEY,
    NRSOSAPPLICATIONID character varying(50),
    SUBMITTEDDATE date,
    RECEIVEDDATE date,
    NOWNUMBER character varying(50),
    STARTWORKDATE date,
    ENDWORKDATE date,
    PROCESSED character varying(1) DEFAULT 'N' ,
    PROCESSEDDATE date

    FOREIGN KEY (APPLICANTCLIENTID) REFERENCES now.client(CLIENTID) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY (SUBMITTERCLIENTID) REFERENCES now.client(CLIENTID) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE now.application (
    MESSAGEID numeric(9,0) PRIMARY KEY,
    TRACKINGNUMBER numeric(9,0),
    APPLICATIONTYPE character varying(100),
    STATUS character varying(60),
    SUBMITTEDDATE date,
    RECEIVEDDATE date,
    APPLICANTCLIENTID numeric(9,0),
    SUBMITTERCLIENTID numeric(9,0),
    NOTICEOFWORKTYPE character varying(300),
    TYPEOFPERMIT character varying(300),
    TYPEOFAPPLICATION character varying(300),
    MINENUMBER character varying(300),
    LATITUDE numeric(9,7),
    LONGITUDE numeric(11,7),
    NAMEOFPROPERTY character varying(4000),
    TENURENUMBERS character varying(4000),
    CROWNGRANTLOTNUMBERS character varying(4000),
    SITEDIRECTIONS character varying(4000),
    FIRSTAIDEQUIPMENTONSITE character varying(4000),
    FIRSTAIDCERTLEVEL character varying(300),
    DESCEXPLORATIONPROGRAM character varying(4000),
    PROPOSEDSTARTDATE date,
    PROPOSEDENDDATE date,
    YEARROUNDSEASONAL character varying(300),
    LANDCOMMUNITYWATERSHED character varying(3),
    LANDPRIVATE character varying(3),
    LANDLEGALDESC character varying(4000),
    ARCHSITESAFFECTED character varying(3),
    SANDGRAVELQUARRYOPERATIONS character varying(3),
    STOREEXPLOSIVESONSITE character varying(3),
    BCEXPLOSIVESPERMITISSUED character varying(3),
    BCEXPLOSIVESPERMITNUMBER character varying(300),
    BCEXPLOSIVESPERMITEXPIRY date,
    CAMPDISTURBEDAREA numeric(14,2),
    CAMPTIMBERVOLUME numeric(14,2),
    BLDGDISTURBEDAREA numeric(14,2),
    BLDGTIMBERVOLUME numeric(14,2),
    STGEDISTURBEDAREA numeric(14,2),
    STGETIMBERVOLUME numeric(14,2),
    FUELLUBSTOREONSITE character varying(3),
    FUELLUBSTORED numeric(14,0),
    FUELLUBSTOREMETHODBULK character varying(3),
    FUELLUBSTOREMETHODBARREL character varying(3),
    CBSFRECLAMATION character varying(4000),
    CBSFRECLAMATIONCOST numeric(14,2),
    MECHTRENCHINGRECLAMATION character varying(4000),
    MECHTRENCHINGRECLAMATIONCOST numeric(14,2),
    EXPSURFACEDRILLRECLAMATION character varying(4000),
    EXPSURFACEDRILLRECLCORESTORAGE character varying(4000),
    EXPSURFACEDRILLRECLAMATIONCOST numeric(14,2),
    EXPACCESSRECLAMATION character varying(4000),
    EXPACCESSRECLAMATIONCOST numeric(14,2),
    SURFACEBULKSAMPLEPROCMETHODS character varying(4000),
    SURFACEBULKSAMPLERECLAMATION character varying(4000),
    SURFACEBULKSAMPLERECLSEPHANDL character varying(4000),
    SURFACEBULKSAMPLERECLDRAINMITI character varying(4000),
    SURFACEBULKSAMPLERECLCOST numeric(14,2),
    UNDEREXPTOTALORE numeric(14,0),
    UNDEREXPTOTALOREUNITS character varying(20),
    UNDEREXPTOTALWASTE numeric(14,0),
    UNDEREXPTOTALWASTEUNITS character varying(20),
    UNDEREXPRECLAMATION character varying(4000),
    UNDEREXPRECLAMATIONCOST numeric(14,2),
    PLACERUNDERGROUNDOPERATIONS character varying(3),
    PLACERHANDOPERATIONS character varying(3),
    PLACERRECLAMATIONAREA numeric(14,2),
    PLACERRECLAMATION character varying(4000),
    PLACERRECLAMATIONCOST numeric(14,2),
    SANDGRVQRYDEPTHOVERBURDEN numeric(14,2),
    SANDGRVQRYDEPTHTOPSOIL numeric(14,2),
    SANDGRVQRYSTABILIZEMEASURES character varying(4000),
    SANDGRVQRYWITHINAGLANDRES character varying(3),
    SANDGRVQRYALRPERMITNUMBER character varying(300),
    SANDGRVQRYLOCALGOVSOILREMBYLAW character varying(3),
    SANDGRVQRYOFFICIALCOMMPLAN character varying(4000),
    SANDGRVQRYLANDUSEZONING character varying(4000),
    SANDGRVQRYENDLANDUSE character varying(4000),
    SANDGRVQRYTOTALMINERES numeric(14,0),
    SANDGRVQRYTOTALMINERESUNITS character varying(20),
    SANDGRVQRYANNUALEXTREST numeric(14,0),
    SANDGRVQRYANNUALEXTRESTUNITS character varying(20),
    SANDGRVQRYRECLAMATION character varying(4000),
    SANDGRVQRYRECLAMATIONBACKFILL character varying(4000),
    SANDGRVQRYRECLAMATIONCOST numeric(14,2),
    SANDGRVQRYGRDWTRAVGDEPTH numeric(14,1),
    SANDGRVQRYGRDWTREXISTINGAREAS character varying(3),
    SANDGRVQRYGRDWTRTESTPITS character varying(3),
    SANDGRVQRYGRDWTRTESTWELLS character varying(3),
    SANDGRVQRYGRDWTROTHER character varying(4000),
    SANDGRVQRYGRDWTRMEASPROTECT character varying(4000),
    SANDGRVQRYIMPACTDISTRES numeric(14,0),
    SANDGRVQRYIMPACTDISTWATER numeric(14,0),
    SANDGRVQRYIMPACTNOISE character varying(4000),
    SANDGRVQRYIMPACTPRVTACCESS character varying(4000),
    SANDGRVQRYIMPACTPREVTDUST character varying(4000),
    SANDGRVQRYIMPACTMINVISUAL character varying(4000),
    CUTLINESEXPLGRIDTOTALLINEKMS numeric(14,0),
    CUTLINESEXPLGRIDTIMBERVOLUME numeric(14,2),
    CUTLINESRECLAMATION character varying(4000),
    CUTLINESRECLAMATIONCOST numeric(14,2),
    PONDSWASTEWATERTREATFACILITY character varying(4000),
    FREEUSEPERMIT character varying(3),
    LICENCETOCUT character varying(3),
    TIMBERTOTALVOLUME numeric(14,2),
    CAMPBUILDSTGETOTALDISTAREA numeric(14,2),
    MECHTRENCHINGTOTALDISTAREA numeric(14,2),
    EXPSURFACEDRILLTOTALDISTAREA numeric(14,2),
    EXPACCESSTOTALDISTAREA numeric(14,2),
    SURFACEBULKSAMPLETOTALDISTAREA numeric(14,2),
    PLACERTOTALDISTAREA numeric(14,2),
    UNDEREXPTOTALDISTAREA numeric(14,2),
    SANDGRVQRYTOTALDISTAREA numeric(14,2),
    PONDSTOTALDISTAREA numeric(14,2),
    RECLCOSTSUBTOTAL numeric(14,2),
    RECLCOSTEXIST numeric(14,2),
    RECLCOSTRECL numeric(14,2),
    RECLCOSTTOTAL numeric(14,2),
    RECLAREASUBTOTAL numeric(14,2),
    RECLAREAEXIST numeric(14,2),
    RECLAREARECL numeric(14,2),
    RECLAREATOTAL numeric(14,2),
    ANYOTHERINFORMATION character varying(4000),
    VFCBCAPPLICATIONURL character varying(4000),
    MESSAGECREATEDDATE date,
    PROCESSED character varying(1) DEFAULT 'N' ,
    PROCESSEDDATE date,
    CUTLINESEXPLGRIDDISTURBEDAREA numeric(14,2),
    PONDSRECYCLED character varying(3),
    PONDSEXFILTRATEDTOGROUND character varying(3),
    PONDSDISCHARGEDTOENV character varying(3),
    PONDSRECLAMATION character varying(4000),
    PONDSRECLAMATIONCOST numeric(14,2),
    SANDGRVQRYTOTALEXISTDISTAREA numeric(14,2),
    NRSOSAPPLICATIONID character varying(50),
    ISBLASTSELECT character varying(3),
    ISTIMBERSELECT character varying(3),

    FOREIGN KEY (APPLICANTCLIENTID) REFERENCES now.client(CLIENTID) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY (SUBMITTERCLIENTID) REFERENCES now.client(CLIENTID) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE now.contact (
    MESSAGEID numeric(9,0) PRIMARY KEY,
    "TYPE" character varying(30),
    ORG_LEGALNAME character varying(250),
    ORG_DOINGBUSINESSAS character varying(150),
    IND_FIRSTNAME character varying(60),
    IND_LASTNAME character varying(60),
    IND_MIDDLENAME character varying(60),
    IND_PHONENUMBER character varying(10),
    DAYPHONENUMBER character varying(10),
    DAYPHONENUMBEREXT character varying(4),
    FAXNUMBER character varying(10),
    EMAIL character varying(60),
    ORG_BCFEDINCORPNUMBER character varying(30),
    ORG_BCREGNUMBER character varying(9),
    ORG_SOCIETYNUMBER character varying(30),
    ORG_HSTREGNUMBER character varying(30),
    ORG_CONTACTNAME character varying(4000),
    MAILINGADDRESSLINE1 character varying(4000),
    CONTACTTYPE character varying(4000),
    CONTACTCERTIFICATIONTYPE character varying(200),
    CONTACTCERTIFICATIONID character varying(4000),
    MAILINGADDRESSLINE2 character varying(60),
    MAILINGADDRESSCITY character varying(100),
    MAILINGADDRESSPROVSTATE character varying(200),
    MAILINGADDRESSCOUNTRY character varying(50),
    MAILINGADDRESSPOSTALZIP character varying(10),
    SEQ_NO numeric(3,0)

    FOREIGN KEY (APPLICANTCLIENTID) REFERENCES now.client(CLIENTID) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY (SUBMITTERCLIENTID) REFERENCES now.client(CLIENTID) DEFERRABLE INITIALLY DEFERRED
);


    mine_report_due_date_type         character varying(3)                    PRIMARY KEY,
    description                       character varying(60)                   NOT NULL   ,
    active_ind                        boolean DEFAULT true                    NOT NULL   ,
    create_user                       character varying(60)                   NOT NULL   ,
    create_timestamp                  timestamp with time zone DEFAULT now()  NOT NULL   ,
    update_user                       character varying(60)                   NOT NULL   ,
    update_timestamp                  timestamp with time zone DEFAULT now()  NOT NULL
);