INSERT INTO sub_division_code
(sub_division_code, description, display_order, create_user, update_user)
VALUES
('AL', 'Alabama', 200, 'system-mds', 'system-mds'),
('AK', 'Alaska', 201, 'system-mds', 'system-mds'),
('AZ', 'Arizona', 202, 'system-mds', 'system-mds'),
('AR', 'Arkansas', 203, 'system-mds', 'system-mds'),
('CA', 'California', 204, 'system-mds', 'system-mds'),
('CO', 'Colorado', 205, 'system-mds', 'system-mds'),
('CT', 'Connecticut', 206, 'system-mds', 'system-mds'),
('DE', 'Delaware', 207, 'system-mds', 'system-mds'),
('FL', 'Florida', 208, 'system-mds', 'system-mds'),
('GA', 'Georgia', 209, 'system-mds', 'system-mds'),
('HI', 'Hawaii', 210, 'system-mds', 'system-mds'),
('ID', 'Idaho', 211, 'system-mds', 'system-mds'),
('IL', 'Illinois', 212, 'system-mds', 'system-mds'),
('IN', 'Indiana', 213, 'system-mds', 'system-mds'),
('IA', 'Iowa', 214, 'system-mds', 'system-mds'),
('KS', 'Kansas', 215, 'system-mds', 'system-mds'),
('KY', 'Kentucky', 216, 'system-mds', 'system-mds'),
('LA', 'Louisiana', 217, 'system-mds', 'system-mds'),
('ME', 'Maine', 218, 'system-mds', 'system-mds'),
('MD', 'Maryland', 219, 'system-mds', 'system-mds'),
('MA', 'Massachusetts', 220, 'system-mds', 'system-mds'),
('MI', 'Michigan', 221, 'system-mds', 'system-mds'),
('MN', 'Minnesota', 222, 'system-mds', 'system-mds'),
('MS', 'Mississippi', 223, 'system-mds', 'system-mds'),
('MO', 'Missouri', 224, 'system-mds', 'system-mds'),
('MT', 'Montana', 225, 'system-mds', 'system-mds'),
('NE', 'Nebraska', 226, 'system-mds', 'system-mds'),
('NV', 'Nevada', 227, 'system-mds', 'system-mds'),
('NH', 'New Hampshire', 228, 'system-mds', 'system-mds'),
('NJ', 'New Jersey', 229, 'system-mds', 'system-mds'),
('NM', 'New Mexico', 230, 'system-mds', 'system-mds'),
('NY', 'New York', 231, 'system-mds', 'system-mds'),
('NC', 'North Carolina', 232, 'system-mds', 'system-mds'),
('ND', 'North Dakota', 233, 'system-mds', 'system-mds'),
('OH', 'Ohio', 234, 'system-mds', 'system-mds'),
('OK', 'Oklahoma', 235, 'system-mds', 'system-mds'),
('OR', 'Oregon', 236, 'system-mds', 'system-mds'),
('PA', 'Pennsylvania', 237, 'system-mds', 'system-mds'),
('RI', 'Rhode Island', 238, 'system-mds', 'system-mds'),
('SC', 'South Carolina', 239, 'system-mds', 'system-mds'),
('SD', 'South Dakota', 240, 'system-mds', 'system-mds'),
('TN', 'Tennessee', 241, 'system-mds', 'system-mds'),
('TX', 'Texas', 242, 'system-mds', 'system-mds'),
('UT', 'Utah', 243, 'system-mds', 'system-mds'),
('VT', 'Vermont', 244, 'system-mds', 'system-mds'),
('VA', 'Virginia', 245, 'system-mds', 'system-mds'),
('WA', 'Washington', 246, 'system-mds', 'system-mds'),
('WV', 'West Virginia', 247, 'system-mds', 'system-mds'),
('WI', 'Wisconsin', 248, 'system-mds', 'system-mds'),
('WY', 'Wyoming', 249, 'system-mds', 'system-mds'),
('DC', 'District of Columbia', 250, 'system-mds', 'system-mds'),
('AS', 'American Samoa', 251, 'system-mds', 'system-mds'),
('GU', 'Guam', 252, 'system-mds', 'system-mds'),
('MP', 'Northern Mariana Islands', 252, 'system-mds', 'system-mds'),
('PR', 'Puerto Rico', 254, 'system-mds', 'system-mds'),
('UM', 'United States Minor Outlying Islands', 255, 'system-mds', 'system-mds'),
('VI', 'Virgin Islands', 256, 'system-mds', 'system-mds')
ON CONFLICT DO NOTHING;