-- This file was generated by the generate_history_table_ddl command
-- The file contains the corresponding history table definition for the minespace_user table
CREATE TABLE minespace_user_version (
	create_user VARCHAR(60), 
	create_timestamp TIMESTAMP WITHOUT TIME ZONE, 
	update_user VARCHAR(60), 
	update_timestamp TIMESTAMP WITHOUT TIME ZONE, 
	deleted_ind BOOLEAN default FALSE,
	user_id INTEGER NOT NULL, 
	bceid_username VARCHAR(100), 
	sub VARCHAR, 
	email VARCHAR, 
	given_name VARCHAR, 
	family_name VARCHAR, 
	display_name VARCHAR, 
	identity_provider VARCHAR, 
	bceid_user_guid VARCHAR, 
	last_logged_in TIMESTAMP WITHOUT TIME ZONE, 
	transaction_id BIGINT NOT NULL, 
	end_transaction_id BIGINT, 
	operation_type SMALLINT NOT NULL, 
	PRIMARY KEY (user_id, transaction_id)
);
CREATE INDEX ix_minespace_user_version_operation_type ON minespace_user_version (operation_type);
CREATE INDEX ix_minespace_user_version_end_transaction_id ON minespace_user_version (end_transaction_id);
CREATE INDEX ix_minespace_user_version_transaction_id ON minespace_user_version (transaction_id);