CREATE TABLE IF NOT EXISTS municipality (
    municipality_guid uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    municipality_name varchar(100) NOT NULL,
    active_ind boolean DEFAULT true NOT NULL,
    create_user character varying(60) NOT NULL,
    create_timestamp timestamp with time zone DEFAULT now() NOT NULL,
    update_user character varying(60) NOT NULL,
    update_timestamp timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE project_summary
    ADD nearest_municipality_guid uuid;

ALTER TABLE project_summary
    ADD CONSTRAINT fk_nearest_municipality
        FOREIGN KEY (nearest_municipality_guid)
            REFERENCES municipality(municipality_guid);

INSERT INTO municipality (municipality_name, create_user, update_user)
VALUES
    ('Village of Valemount', 'system-mds', 'system-mds'),
    ('District of Kitimat', 'system-mds', 'system-mds'),
    ('The Corporation of the Village of Hazelton', 'system-mds', 'system-mds'),
    ('District of New Hazelton', 'system-mds', 'system-mds'),
    ('District of Stewart', 'system-mds', 'system-mds'),
    ('City of Terrace', 'system-mds', 'system-mds'),
    ('Northern Rockies Regional Municipality', 'system-mds', 'system-mds'),
    ('District of Tumbler Ridge', 'system-mds', 'system-mds'),
    ('District of Chetwynd', 'system-mds', 'system-mds'),
    ('Village of Anmore', 'system-mds', 'system-mds'),
    ('Village of Belcarra', 'system-mds', 'system-mds'),
    ('Bowen Island Municipality', 'system-mds', 'system-mds'),
    ('City of Burnaby', 'system-mds', 'system-mds'),
    ('City of Coquitlam', 'system-mds', 'system-mds'),
    ('City of Delta', 'system-mds', 'system-mds'),
    ('City of Port Coquitlam', 'system-mds', 'system-mds'),
    ('City of Port Moody', 'system-mds', 'system-mds'),
    ('City of Richmond', 'system-mds', 'system-mds'),
    ('City of Surrey', 'system-mds', 'system-mds'),
    ('City of Vancouver', 'system-mds', 'system-mds'),
    ('District Municipality of West Vancouver', 'system-mds', 'system-mds'),
    ('City of White Rock', 'system-mds', 'system-mds'),
    ('Village of Lions Bay', 'system-mds', 'system-mds'),
    ('The Corporation of the Township of Langley', 'system-mds', 'system-mds'),
    ('The Corporation of the District of North Vancouver', 'system-mds', 'system-mds'),
    ('Village of Keremeos', 'system-mds', 'system-mds'),
    ('Town of Osoyoos', 'system-mds', 'system-mds'),
    ('The Corporation of the City of Penticton', 'system-mds', 'system-mds'),
    ('Town of Princeton', 'system-mds', 'system-mds'),
    ('Town of Oliver', 'system-mds', 'system-mds'),
    ('The Corporation of the District of Summerland', 'system-mds', 'system-mds'),
    ('District of Lillooet', 'system-mds', 'system-mds'),
    ('District of Squamish', 'system-mds', 'system-mds'),
    ('Resort Municipality of Whistler', 'system-mds', 'system-mds'),
    ('Village of Pemberton', 'system-mds', 'system-mds'),
    ('The Corporation of the Village of Ashcroft', 'system-mds', 'system-mds'),
    ('Village of Chase', 'system-mds', 'system-mds'),
    ('Village of Clinton', 'system-mds', 'system-mds'),
    ('City of Kamloops', 'system-mds', 'system-mds'),
    ('District of Logan Lake', 'system-mds', 'system-mds'),
    ('District of Barriere', 'system-mds', 'system-mds'),
    ('Village of Cache Creek', 'system-mds', 'system-mds'),
    ('District of Clearwater', 'system-mds', 'system-mds'),
    ('Village of Lytton', 'system-mds', 'system-mds'),
    ('City of Merritt', 'system-mds', 'system-mds'),
    ('City of Langley', 'system-mds', 'system-mds'),
    ('City of Maple Ridge', 'system-mds', 'system-mds'),
    ('City of New Westminster', 'system-mds', 'system-mds'),
    ('City of North Vancouver', 'system-mds', 'system-mds'),
    ('City of Pitt Meadows', 'system-mds', 'system-mds'),
    ('The Corporation of the City of Dawson Creek', 'system-mds', 'system-mds'),
    ('City of Fort St John', 'system-mds', 'system-mds'),
    ('District of Hudsons Hope', 'system-mds', 'system-mds'),
    ('The Corporation of the Village of Pouce Coupe', 'system-mds', 'system-mds'),
    ('District of Taylor', 'system-mds', 'system-mds'),
    ('Village of Daajing Giids', 'system-mds', 'system-mds'),
    ('Village of Masset', 'system-mds', 'system-mds'),
    ('Village of Port Clements', 'system-mds', 'system-mds'),
    ('District of Port Edward', 'system-mds', 'system-mds'),
    ('City of Prince Rupert', 'system-mds', 'system-mds'),
    ('City of Kelowna', 'system-mds', 'system-mds'),
    ('District of Lake Country', 'system-mds', 'system-mds'),
    ('The Corporation of the District of Peachland', 'system-mds', 'system-mds'),
    ('City of West Kelowna', 'system-mds', 'system-mds'),
    ('City of Abbotsford', 'system-mds', 'system-mds'),
    ('City of Chilliwack', 'system-mds', 'system-mds'),
    ('Village of Harrison Hot Springs', 'system-mds', 'system-mds'),
    ('District of Hope', 'system-mds', 'system-mds'),
    ('District of Kent', 'system-mds', 'system-mds'),
    ('City of Mission', 'system-mds', 'system-mds'),
    ('The Corporation of the Village of Burns Lake', 'system-mds', 'system-mds'),
    ('District of Fort St James', 'system-mds', 'system-mds'),
    ('Village of Fraser Lake', 'system-mds', 'system-mds'),
    ('Village of Granisle', 'system-mds', 'system-mds'),
    ('District of Houston', 'system-mds', 'system-mds'),
    ('Town of Smithers', 'system-mds', 'system-mds'),
    ('The Corporation of the Village of Telkwa', 'system-mds', 'system-mds'),
    ('District of Vanderhoof', 'system-mds', 'system-mds'),
    ('District of 100 Mile House', 'system-mds', 'system-mds'),
    ('City of Quesnel', 'system-mds', 'system-mds'),
    ('District of Wells', 'system-mds', 'system-mds'),
    ('City of Williams Lake', 'system-mds', 'system-mds'),
    ('District of Mackenzie', 'system-mds', 'system-mds'),
    ('The Corporation of the Village of McBride', 'system-mds', 'system-mds'),
    ('City of Prince George', 'system-mds', 'system-mds'),
    ('Village of Midway', 'system-mds', 'system-mds'),
    ('Village of Montrose', 'system-mds', 'system-mds'),
    ('City of Rossland', 'system-mds', 'system-mds'),
    ('City of Trail', 'system-mds', 'system-mds'),
    ('Village of Warfield', 'system-mds', 'system-mds'),
    ('The Corporation of the Village of Lumby', 'system-mds', 'system-mds'),
    ('The Corporation of the Township of Spallumcheen', 'system-mds', 'system-mds'),
    ('The Corporation of the City of Vernon', 'system-mds', 'system-mds'),
    ('City of Port Alberni', 'system-mds', 'system-mds'),
    ('Corporation of the Village of Tofino', 'system-mds', 'system-mds'),
    ('District of Ucluelet', 'system-mds', 'system-mds'),
    ('The Corporation of the District of Central Saanich', 'system-mds', 'system-mds'),
    ('City of Colwood', 'system-mds', 'system-mds'),
    ('The Corporation of the Township of Esquimalt', 'system-mds', 'system-mds'),
    ('District of Highlands', 'system-mds', 'system-mds'),
    ('City of Langford', 'system-mds', 'system-mds'),
    ('District of Metchosin', 'system-mds', 'system-mds'),
    ('District of North Saanich', 'system-mds', 'system-mds'),
    ('The Corporation of the District of Oak Bay', 'system-mds', 'system-mds'),
    ('The Corporation of the District of Saanich', 'system-mds', 'system-mds'),
    ('Town of Sidney', 'system-mds', 'system-mds'),
    ('The Corporation of the Village of Fruitvale', 'system-mds', 'system-mds'),
    ('City of Armstrong', 'system-mds', 'system-mds'),
    ('The Corporation of the District of Coldstream', 'system-mds', 'system-mds'),
    ('The Corporation of the City of Enderby', 'system-mds', 'system-mds'),
    ('Sun Peaks Mountain Resort Municipality', 'system-mds', 'system-mds'),
    ('The Corporation of the City of Nelson', 'system-mds', 'system-mds'),
    ('Village of Slocan', 'system-mds', 'system-mds'),
    ('The Corporation of the Village of Salmo', 'system-mds', 'system-mds'),
    ('The Corporation of the Village of Silverton', 'system-mds', 'system-mds'),
    ('Town of Creston', 'system-mds', 'system-mds'),
    ('Village of Kaslo', 'system-mds', 'system-mds'),
    ('Village of New Denver', 'system-mds', 'system-mds'),
    ('Village of Nakusp', 'system-mds', 'system-mds'),
    ('City of Castlegar', 'system-mds', 'system-mds'),
    ('Town of Golden', 'system-mds', 'system-mds'),
    ('City of Revelstoke', 'system-mds', 'system-mds'),
    ('City of Salmon Arm', 'system-mds', 'system-mds'),
    ('The Corporation of the District of Sicamous', 'system-mds', 'system-mds'),
    ('Village of Canal Flats', 'system-mds', 'system-mds'),
    ('The Corporation of the City of Cranbrook', 'system-mds', 'system-mds'),
    ('District of Elkford', 'system-mds', 'system-mds'),
    ('The Corporation of the City of Fernie', 'system-mds', 'system-mds'),
    ('District of Invermere', 'system-mds', 'system-mds'),
    ('City of Kimberley', 'system-mds', 'system-mds'),
    ('Village of Radium Hot Springs', 'system-mds', 'system-mds'),
    ('District of Sparwood', 'system-mds', 'system-mds'),
    ('City of Grand Forks', 'system-mds', 'system-mds'),
    ('City of Greenwood', 'system-mds', 'system-mds'),
    ('District of Sooke', 'system-mds', 'system-mds'),
    ('The Corporation of the City of Victoria', 'system-mds', 'system-mds'),
    ('Town of View Royal', 'system-mds', 'system-mds'),
    ('Village of Cumberland', 'system-mds', 'system-mds'),
    ('Town of Comox', 'system-mds', 'system-mds'),
    ('The Corporation of the City of Courtenay', 'system-mds', 'system-mds'),
    ('The Corporation of the City of Duncan', 'system-mds', 'system-mds'),
    ('Town of Ladysmith', 'system-mds', 'system-mds'),
    ('Town of Lake Cowichan', 'system-mds', 'system-mds'),
    ('The Corporation of the District of North Cowichan', 'system-mds', 'system-mds'),
    ('The Corporation of the Village of Alert Bay', 'system-mds', 'system-mds'),
    ('Village of Port Alice', 'system-mds', 'system-mds'),
    ('District of Port Hardy', 'system-mds', 'system-mds'),
    ('Town of Port McNeill', 'system-mds', 'system-mds'),
    ('City of Parksville', 'system-mds', 'system-mds'),
    ('District of Lantzville', 'system-mds', 'system-mds'),
    ('City of Nanaimo', 'system-mds', 'system-mds'),
    ('Town of Qualicum Beach', 'system-mds', 'system-mds'),
    ('City of Powell River', 'system-mds', 'system-mds'),
    ('Town of Gibsons', 'system-mds', 'system-mds'),
    ('District of Sechelt', 'system-mds', 'system-mds'),
    ('City of Campbell River', 'system-mds', 'system-mds'),
    ('Village of Gold River', 'system-mds', 'system-mds'),
    ('Village of Sayward', 'system-mds', 'system-mds'),
    ('Village of Tahsis', 'system-mds', 'system-mds'),
    ('The Corporation of the Village of Zeballos', 'system-mds', 'system-mds');