-- This file was generated by the generate_history_table_ddl command
-- The file contains the corresponding history table definition for the {table} table
CREATE TABLE mine_report_permit_requirement_version (
	create_user VARCHAR(255), 
	create_timestamp TIMESTAMP WITHOUT TIME ZONE, 
	update_user VARCHAR(255), 
	update_timestamp TIMESTAMP WITHOUT TIME ZONE, 
	deleted_ind BOOLEAN, 
	mine_report_permit_requirement_id INTEGER NOT NULL, 
	due_date_period_months INTEGER, 
	initial_due_date DATE, 
	report_name VARCHAR(255), 
	active_ind BOOLEAN, 
	cim_or_cpo cim_or_cpo_type, 
	ministry_recipient ministry_recipient_type[], 
	permit_amendment_id INTEGER, 
	transaction_id BIGINT NOT NULL, 
	end_transaction_id BIGINT, 
	operation_type SMALLINT NOT NULL, 
	PRIMARY KEY (mine_report_permit_requirement_id, transaction_id)
);
CREATE INDEX ix_mine_report_permit_requirement_version_end_transaction_id ON mine_report_permit_requirement_version (end_transaction_id);
CREATE INDEX ix_mine_report_permit_requirement_version_operation_type ON mine_report_permit_requirement_version (operation_type);
CREATE INDEX ix_mine_report_permit_requirement_version_transaction_id ON mine_report_permit_requirement_version (transaction_id);
