-- This file was generated by the generate_history_table_ddl command
-- The file contains the corresponding history table definition for the {table} table
CREATE TABLE permit_condition_review_assignment_version (
	create_user VARCHAR(60), 
	create_timestamp TIMESTAMP WITHOUT TIME ZONE, 
	update_user VARCHAR(60), 
	update_timestamp TIMESTAMP WITHOUT TIME ZONE, 
	deleted_ind BOOLEAN,
	condition_review_assignment_guid UUID NOT NULL, 
	permit_amendment_id INTEGER, 
	condition_category_code VARCHAR, 
	user_sub VARCHAR, 
	transaction_id BIGINT NOT NULL, 
	end_transaction_id BIGINT, 
	operation_type SMALLINT NOT NULL, 
	PRIMARY KEY (condition_review_assignment_guid, transaction_id)
);
CREATE INDEX ix_permit_condition_review_assignment_version_operation_type ON permit_condition_review_assignment_version (operation_type);
CREATE INDEX ix_permit_condition_review_assignment_version_transaction_id ON permit_condition_review_assignment_version (transaction_id);
CREATE INDEX ix_permit_condition_review_assignment_version_end_trans_44f2 ON permit_condition_review_assignment_version (end_transaction_id);
