-- compliance_article_emli_contact_xref (mine_report_notification) table. This cotains the parameters that needs to decide the notifications when crr submitted
CREATE TABLE IF NOT EXISTS mine_report_notification
(
    compliance_article_emli_contact_xref_guid   uuid    DEFAULT gen_random_uuid() NOT NULL,
    compliance_article_id                       integer                           NOT NULL,
    contact_guid	                              uuid	                            NOT NULL,
    is_major_mine                               boolean default false             NOT NULL,
    is_regional_mine                            boolean default false             NOT NULL,

    FOREIGN KEY (compliance_article_id) REFERENCES compliance_article(compliance_article_id) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY (contact_guid) REFERENCES emli_contact(contact_guid) DEFERRABLE INITIALLY DEFERRED,
    PRIMARY KEY (compliance_article_emli_contact_xref_guid)
);
ALTER TABLE mine_report_notification OWNER TO mds;

CREATE TEMP TABLE IF NOT EXISTS temp_article_section_email_mapping (
	mapping_guid        uuid      DEFAULT gen_random_uuid(),
	"section"           varchar,
	sub_section         varchar,
	paragraph					  varchar,
	sub_paragraph				varchar,
	is_major					  boolean,
	is_regional					boolean,
	email						    varchar
);

INSERT INTO temp_article_section_email_mapping(
    "section",
    sub_section,
	  paragraph,
	  sub_paragraph,
	  is_major,
	  is_regional,
	  email
) 
VALUES	-- Mapping compliance_article(section,sub_section,paragraph,sub_paragraph) and mine detials: (is_major,is_regional,email): mds@gov.bc.ca is used as the default email
	('1','6','4',NULL,'false','false','mines.inquiries@gov.bc.ca'),
	('1','6','4',NULL,'false','false','mine.ergonomics@gov.bc.ca'),
	('1','6','5',NULL,'false','false','mines.inquiries@gov.bc.ca'),
	('1','6','6',NULL,'false','false','mines.inquiries@gov.bc.ca'),
	('1','6','9','h','false','false','mines.inquiries@gov.bc.ca'),
	('1','6','9','h','false','false','mine.ergonomics@gov.bc.ca'),
	('1','6','9',NULL,'false','false','mines.inquiries@gov.bc.ca'),
	('1','6','12','(c)','false','false','mines.inquiries@gov.bc.ca'),
	('1','7','1',NULL,'false','false','mines.inquiries@gov.bc.ca'),
	('1','7','1','(1)(a)','false','false','mineincidents@gov.bc.ca'),
	('1','7','1','(1)(b)','false','false','mineincidents@gov.bc.ca'),
	('1','7','1','(1)(b)','false','false','minesdrg@victoria1.gov.bc.ca'),
	('1','7','1','(2)(a)','false','false','mineincidents@gov.bc.ca'),
	('1','7','1','(2)(a)','false','false','minesdrg@victoria1.gov.bc.ca'),
	('1','7','1','(2)(a)','false','false','technicalcompliance@gov.bc.ca'),
	('1','7','1','(2)(b)','false','false','mineincidents@gov.bc.ca'),
	('1','7','1','(2)(b)','false','false','minesdrg@victoria1.gov.bc.ca'),
	('1','7','1','(2)(c)','false','false','mineincidents@gov.bc.ca'),
	('1','7','1','(2)(c)','false','false','minesdrg@victoria1.gov.bc.ca'),
	('1','7','1','(2)(c)','false','false','technicalcompliance@gov.bc.ca'),
	('1','7','1','(2)(d)','false','false','mineincidents@gov.bc.ca'),
	('1','7','1','(2)(d)','false','false','minesdrg@victoria1.gov.bc.ca'),
	('1','7','1','(2)(e)','false','false','mineincidents@gov.bc.ca'),
	('1','7','1','(2)(e)','false','false','minesdrg@victoria1.gov.bc.ca'),
	('1','7','1','(2)(f)','false','false','mineincidents@gov.bc.ca'),
	('1','7','1','(2)(f)','false','false','minesdrg@victoria1.gov.bc.ca'),
	('1','7','1','(2)(g)','false','false','mineincidents@gov.bc.ca'),
	('1','7','1','(2)(g)','false','false','minesdrg@victoria1.gov.bc.ca'),
	('1','7','1','(2)(h)','false','false','mineincidents@gov.bc.ca'),
	('1','7','1','(2)(h)','false','false','minesdrg@victoria1.gov.bc.ca'),
	('1','7','1','(2)(h)','false','false','technicalcompliance@gov.bc.ca'),
	('1','7','1',NULL,'false','false','mineincidents@gov.bc.ca'),
	('1','7','1',NULL,'false','false','minesdrg@victoria1.gov.bc.ca'),
	('1','7','1',NULL,'false','false','technicalcompliance@gov.bc.ca'),
	('1','7','2','(1)(b)','false','false','mineincidents@gov.bc.ca'),
	('1','7','2','(1)(b)','false','false','minesdrg@victoria1.gov.bc.ca'),
	('1','7','2','(1)(b)','false','false','technicalcompliance@gov.bc.ca'),
	('1','7','3',NULL,'false','false','mines.inquiries@gov.bc.ca'),
	('1','7','4',NULL,'false','false','mines.inquiries@gov.bc.ca'),
	('1','9','2','1','false','false','mines.inquiries@gov.bc.ca'),
	('1','9','2','1','false','false','mine.ergonomics@gov.bc.ca'),
	('1','9','2','2','false','false','mines.inquiries@gov.bc.ca'),
	('1','9','2','2','false','false','mine.ergonomics@gov.bc.ca'),
	('1','9','2',NULL,'false','false','mines.inquiries@gov.bc.ca'),
	('1','9','3',NULL,'false','false','mines.inquiries@gov.bc.ca'),
	('1','10','7','2','false','false','mines.inquiries@gov.bc.ca'),
	('1','11','2',NULL,'false','false','mines.inquiries@gov.bc.ca'),
	('2','1','3',NULL,'false','false','mines.inquiries@gov.bc.ca'),
	('2','1','3',NULL,'false','false','mine.occhealth@gov.bc.ca'),
	('2','2','1',NULL,'false','false','mines.inquiries@gov.bc.ca'),
	('2','3','2',NULL,'false','false','mines.inquiries@gov.bc.ca'),
	('2','3','2',NULL,'false','false','mine.occhealth@gov.bc.ca'),
	('2','3','11','5','false','false','mines.inquiries@gov.bc.ca'),
	('2','3','11','5','false','false','mine.occhealth@gov.bc.ca'),
	('2','8','6',NULL,'false','false','mines.inquiries@gov.bc.ca'),
	('2','10','1',NULL,'false','false','mines.inquiries@gov.bc.ca'),
	('2','10','1',NULL,'false','false','mine.occhealth@gov.bc.ca'),
	('2','11','10',NULL,'false','false','mines.inquiries@gov.bc.ca'),
	('2','12','1',NULL,'false','false','mines.inquiries@gov.bc.ca'),
	('2','12','1',NULL,'false','false','mine.occhealth@gov.bc.ca'),
	('2','12','4','2','false','false','mines.inquiries@gov.bc.ca'),
	('2','12','4','2','false','false','mine.occhealth@gov.bc.ca'),
	('3','4','2',NULL,'false','false','mines.inquiries@gov.bc.ca'),
	('3','7','1','1','false','true','mines.inquiries@gov.bc.ca'),
	('3','7','1','4','false','false','mines.inquiries@gov.bc.ca'),
	('3','13','4',NULL,'false','false','mines.inquiries@gov.bc.ca'),
	('4','3','3','1','false','false','mines.inquiries@gov.bc.ca'),
	('4','3','3','1','false','false','mine.safety@gov.bc.ca'),
	('4','3','4','1','false','false','mines.inquiries@gov.bc.ca'),
	('4','3','4','1','false','false','mine.safety@gov.bc.ca'),
	('4','7','1','1','false','false','mines.inquiries@gov.bc.ca'),
	('4','7','1','1','false','false','mine.safety@gov.bc.ca'),
	('4','9','1',NULL,'false','false','mines.inquiries@gov.bc.ca'),
	('4','9','1',NULL,'false','false','mine.safety@gov.bc.ca'),
	('4','10','1','2','false','false','mines.inquiries@gov.bc.ca'),
	('4','10','1','2','false','false','mine.safety@gov.bc.ca'),
	('5','2','1',NULL,'false','false','mines.inquiries@gov.bc.ca'),
	('5','2','1',NULL,'false','false','mine.safety@gov.bc.ca'),
	('5','7','2',NULL,'true','true','mines.inquiries@gov.bc.ca'),
	('5','7','2',NULL,'true','true','mine.safety@gov.bc.ca'),
	('6','2','1',NULL,'true','true','mines.inquiries@gov.bc.ca'),
	('6','2','2',NULL,'false','false','mines.inquiries@gov.bc.ca'),
	('6','8','1',NULL,'false','false','mines.inquiries@gov.bc.ca'),
	('6','9','1',NULL,'true','false','mines.inquiries@gov.bc.ca'),
	('6','9','1',NULL,'true','false','mine.safety@gov.bc.ca'),
	('6','10','1','7','true','false','mines.inquiries@gov.bc.ca'),
	('6','42','3',NULL,'false','false','mines.inquiries@gov.bc.ca'),
	('7','2','4',NULL,'false','false','mines.inquiries@gov.bc.ca'),
	('7','2','4',NULL,'false','false','mine.safety@gov.bc.ca'),
	('7','4','4',NULL,'false','false','mines.inquiries@gov.bc.ca'),
	('7','4','4',NULL,'false','false','mine.safety@gov.bc.ca'),
	('7','4','5',NULL,'false','false','mines.inquiries@gov.bc.ca'),
	('7','4','5',NULL,'false','false','mine.safety@gov.bc.ca'),
	('7','4','6',NULL,'false','false','mines.inquiries@gov.bc.ca'),
	('7','4','6',NULL,'false','false','mine.safety@gov.bc.ca'),
	('7','4','13',NULL,'false','false','mines.inquiries@gov.bc.ca'),
	('7','4','13',NULL,'false','false','mine.safety@gov.bc.ca'),
	('7','5','13',NULL,'false','false','mines.inquiries@gov.bc.ca'),
	('7','5','13',NULL,'false','false','mine.safety@gov.bc.ca'),
	('7','6','6',NULL,'true','false','mines.inquiries@gov.bc.ca'),
	('7','6','6',NULL,'true','false','mine.safety@gov.bc.ca'),
	('7','7','9',NULL,'false','false','mines.inquiries@gov.bc.ca'),
	('7','7','9',NULL,'false','false','mine.safety@gov.bc.ca'),
	('7','9','4',NULL,'false','false','mines.inquiries@gov.bc.ca'),
	('7','9','4',NULL,'false','false','mine.safety@gov.bc.ca'),
	('7','9','7',NULL,'false','false','mines.inquiries@gov.bc.ca'),
	('7','9','7',NULL,'false','false','mine.safety@gov.bc.ca'),
	('7',NULL,NULL,NULL,'false','false','mines.inquiries@gov.bc.ca'),
	('8','3','4',NULL,'false','false','mines.inquiries@gov.bc.ca'),
	('8','3','5',NULL,'false','false','mines.inquiries@gov.bc.ca'),
	('8','3','9','2','false','false','mines.inquiries@gov.bc.ca'),
	('8','7','2','2','false','false','mines.inquiries@gov.bc.ca'),
	('8','8','1','2','false','false','mines.inquiries@gov.bc.ca'),
	('9','1','1',NULL,'false','true','mds@gov.bc.ca'),
	('9','2','1','3','true','true','mines.inquiries@gov.bc.ca'),
	('9','5','1','3','false','true','mds@gov.bc.ca'),
	('9','7','1','2','false','true','mds@gov.bc.ca'),
	('9','7','1',NULL,'false','true','mds@gov.bc.ca'),
	('9','10','1','3','false','true','mds@gov.bc.ca'),
	('9','10','1',NULL,'false','true','mds@gov.bc.ca'),
	('9','13','1','1','false','true','mds@gov.bc.ca'),
	('9','13','1','5','true','true','mds@gov.bc.ca'),
	('9','13','1','6','false','true','mds@gov.bc.ca'),
	('10','1','2',NULL,'true','true','mds@gov.bc.ca'),
	('10','1','3',NULL,'true','true','mds@gov.bc.ca'),
	('10','1','5',NULL,'true','true','mds@gov.bc.ca'),
	('10','1','6',NULL,'true','true','mds@gov.bc.ca'),
	('10','1','6',NULL,'true','true','mds@gov.bc.ca'),
	('10','1','7',NULL,'true','true','mds@gov.bc.ca'),
	('10','1','8',NULL,'true','true','mds@gov.bc.ca'),
	('10','1','9',NULL,'true','true','mds@gov.bc.ca'),
	('10','1','9',NULL,'true','true','mds@gov.bc.ca'),
	('10','1','10',NULL,'true','true','mds@gov.bc.ca'),
	('10','1','11',NULL,'true','true','mds@gov.bc.ca'),
	('10','1','11',NULL,'true','true','mds@gov.bc.ca'),
	('10','1','12',NULL,'true','true','mds@gov.bc.ca'),
	('10','1','12',NULL,'true','true','mds@gov.bc.ca'),
	('10','1','15',NULL,'true','false','mds@gov.bc.ca'),
	('10','1','16',NULL,'true','false','mds@gov.bc.ca'),
	('10','1','18',NULL,'true','true','mds@gov.bc.ca'),
	('10','3','2',NULL,'true','true','mds@gov.bc.ca'),
	('10','3','3',NULL,'true','true','mds@gov.bc.ca'),
	('10','4','1','3','true','false','technicalcompliance@gov.bc.ca'),
	('10','4','1',NULL,'true','true','technicalcompliance@gov.bc.ca'),
	('10','4','2','3','true','false','technicalcompliance@gov.bc.ca'),
	('10','4','2','(1)a','true','false','technicalcompliance@gov.bc.ca'),
	('10','4','2','(1)d','true','false','technicalcompliance@gov.bc.ca'),
	('10','4','2','(1)e','true','false','technicalcompliance@gov.bc.ca'),
	('10','4','4','(a)','true','true','technicalcompliance@gov.bc.ca'),
	('10','4','4','(b)','true','false','technicalcompliance@gov.bc.ca'),
	('10','4','4','(c)','true','false','technicalcompliance@gov.bc.ca'),
	('10','4','4','(d)','true','false','technicalcompliance@gov.bc.ca'),
	('10','4','4','(e)','true','false','technicalcompliance@gov.bc.ca'),
	('10','4','4','(f)','true','false','technicalcompliance@gov.bc.ca'),
	('10','4','5','a (major mine)','true','false','technicalcompliance@gov.bc.ca'),
	('10','4','5','a (regional mine)','false','true','technicalcompliance@gov.bc.ca'),
	('10','4','5','b','true','false','technicalcompliance@gov.bc.ca'),
	('10','4','5','c','true','false','technicalcompliance@gov.bc.ca'),
	('10','4','5',NULL,'true','true','mds@gov.bc.ca'),
	('10','5','1','1','true','true','mines.inquiries@gov.bc.ca'),
	('10','5','1','1','true','true','mine.safety@gov.bc.ca'),
	('10','5','1','1','true','true','technicalcompliance@gov.bc.ca'),
	('10','5','1',NULL,'true','false','mds@gov.bc.ca'),
	('10','5','2',NULL,'true','false','mds@gov.bc.ca'),
	('10','5','2',NULL,'true','false','technicalcompliance@gov.bc.ca'),
	('10','5','3',NULL,'true','false','mds@gov.bc.ca'),
	('10','5','5',NULL,'true','false','mds@gov.bc.ca'),
	('10','5','6',NULL,'true','false','mds@gov.bc.ca'),
	('10','5','7','2','true','true','technicalcompliance@gov.bc.ca'),
	('10','5','9',NULL,'true','false','mds@gov.bc.ca'),
	('10','5','10',NULL,'true','false','mds@gov.bc.ca'),
	('10','5','11',NULL,'true','false','mds@gov.bc.ca'),
	('10','5','12',NULL,'true','false','mds@gov.bc.ca'),
	('10','6','1',NULL,'true','true','mds@gov.bc.ca'),
	('10','6','2',NULL,'true','false','mds@gov.bc.ca'),
	('10','6','2','(2)(a)','true','true','mds@gov.bc.ca'),
	('10','6','4',NULL,'true','false','mds@gov.bc.ca'),
	('10','6','5',NULL,'true','false','mds@gov.bc.ca'),
	('10','6','6',NULL,'true','false','mds@gov.bc.ca'),
	('10','6','7',NULL,'true','false','mds@gov.bc.ca'),
	('10','6','8',NULL,'true','false','mds@gov.bc.ca'),
	('10','6','8',NULL,'true','true','mds@gov.bc.ca'),
	('10','6','9',NULL,'true','true','mds@gov.bc.ca'),
	('10','6','10',NULL,'true','true','mds@gov.bc.ca'),
	('10','6','11',NULL,'true','true','mds@gov.bc.ca'),
	('10','6','12',NULL,'true','true','mds@gov.bc.ca'),
	('10','6','13',NULL,'true','true','mds@gov.bc.ca'),
	('10','6','14',NULL,'true','true','mds@gov.bc.ca'),
	('10','6',NULL,NULL,'true','true','mds@gov.bc.ca'),
	('10','7','14',NULL,'true','true','mds@gov.bc.ca'),
	('10','7','15',NULL,'true','true','mds@gov.bc.ca'),
	('10','7','16',NULL,'true','true','mds@gov.bc.ca'),
	('10','7','17',NULL,'true','true','mds@gov.bc.ca'),
	('10','7','17',NULL,'true','true','technicalcompliance@gov.bc.ca'),
	('10','7','18',NULL,'true','true','technicalcompliance@gov.bc.ca'),
	('10','7','18',NULL,'true','true','mds@gov.bc.ca'),
	('10','7','19',NULL,'true','true','mds@gov.bc.ca'),
	('10','7','20',NULL,'true','true','mds@gov.bc.ca'),
	('10','7','21',NULL,'true','true','mds@gov.bc.ca'),
	('10','7','21',NULL,'true','true','mds@gov.bc.ca'),
	('10','7','22',NULL,'true','true','mds@gov.bc.ca'),
	('10','7','23',NULL,'true','true','mds@gov.bc.ca'),
	('10','7','24',NULL,'true','true','mds@gov.bc.ca'),
	('10','7','25',NULL,'true','true','mds@gov.bc.ca'),
	('10','7','26',NULL,'true','true','mds@gov.bc.ca'),
	('10','7','27',NULL,'true','true','mds@gov.bc.ca'),
	('10','7','28',NULL,'true','true','mds@gov.bc.ca'),
	('10','7','29',NULL,'true','true','mds@gov.bc.ca'),
	('10','7','30',NULL,'true','true','mds@gov.bc.ca'),
	('10','7','31',NULL,'true','true','mds@gov.bc.ca'),
	('10',NULL,NULL,NULL,'true','true','mds@gov.bc.ca'),
	('11','1',NULL,NULL,'true','true','mds@gov.bc.ca'),
	('17',NULL,NULL,NULL,'true','true','Abandoned.Mines@gov.bc.ca'),
	('18',NULL,NULL,NULL,'true','true','mds@gov.bc.ca'),
	('19',NULL,NULL,NULL,'true','true','mds@gov.bc.ca'),
	('20',NULL,NULL,NULL,'true','true','mds@gov.bc.ca'),
	('27',NULL,NULL,NULL,'true','true','mds@gov.bc.ca'),
	('28',NULL,NULL,NULL,'true','true','mds@gov.bc.ca'),
	('31',NULL,NULL,NULL,'true','true','mds@gov.bc.ca'),
	('33',NULL,NULL,NULL,'true','true','mds@gov.bc.ca'),
	('17',NULL,NULL,NULL,'true','true','Abandoned.Mines@gov.bc.ca');

INSERT INTO mine_report_notification (
    compliance_article_id,
    contact_guid,
    is_major_mine,
    is_regional_mine
 )
	SELECT
        ca.compliance_article_id,
        ec.contact_guid, 
        tmp.is_major,
        tmp.is_regional
        FROM temp_article_section_email_mapping tmp
        INNER JOIN emli_contact ec 
        ON tmp.email = ec.email
        
        INNER JOIN compliance_article ca
        ON tmp."section" = ca."section" 
        AND
        	(CASE 
	        	WHEN tmp.sub_section IS NOT NULL AND tmp.paragraph IS NOT NULL AND tmp.sub_paragraph IS NOT NULL
	        		THEN ca.sub_section = tmp.sub_section 
	        			AND ca.paragraph = tmp.paragraph 
	        			AND ca.sub_paragraph = tmp.sub_paragraph 
	        	
	        	WHEN tmp.sub_section IS NOT NULL AND tmp.paragraph IS NOT NULL
	        		THEN ca.sub_section = tmp.sub_section 
	        			AND ca.paragraph = tmp.paragraph 

	        	WHEN tmp.sub_section IS NOT NULL
	        		THEN ca.sub_section = tmp.sub_section 
			    END);

DROP TABLE temp_article_section_email_mapping;
