-- This file was generated by the generate_history_table_ddl command
-- The file contains the data migration to backfill history records for the {table} table
with transaction AS (insert into transaction(id) values(DEFAULT) RETURNING id)
insert into now_application_tier_version (transaction_id, operation_type, end_transaction_id, "create_user", "create_timestamp", "update_user", "update_timestamp", "now_application_tier_id", "now_application_id", "notice_of_work_tier_code", "description")
select t.id, '0', null, "create_user", "create_timestamp", "update_user", "update_timestamp", "now_application_tier_id", "now_application_id", "notice_of_work_tier_code", "description"
from now_application_tier,transaction t;
