-- This file was generated by the generate_history_table_ddl command
-- The file contains the data migration to backfill history records for the {table} table
with transaction AS (insert into transaction(id) values(DEFAULT) RETURNING id)
insert into mine_tailings_storage_facility_version (transaction_id, operation_type, end_transaction_id, "create_user", "create_timestamp", "update_user", "update_timestamp", "mine_tailings_storage_facility_guid", "mine_guid", "mine_tailings_storage_facility_name", "latitude", "longitude", "consequence_classification_status_code", "itrb_exemption_status_code", "tsf_operating_status_code", "notes", "storage_location", "facility_type", "tailings_storage_facility_type", "mines_act_permit_no")
select t.id, '0', null, "create_user", "create_timestamp", "update_user", "update_timestamp", "mine_tailings_storage_facility_guid", "mine_guid", "mine_tailings_storage_facility_name", "latitude", "longitude", "consequence_classification_status_code", "itrb_exemption_status_code", "tsf_operating_status_code", "notes", "storage_location", "facility_type", "tailings_storage_facility_type", "mines_act_permit_no" from mine_tailings_storage_facility,transaction t
;
