-- This file was generated by the generate_history_table_ddl command
-- The file contains the corresponding history table definition for the {table} table
CREATE TABLE mine_report_req_permit_condition_xref_version (
	create_user VARCHAR(60) DEFAULT 'system', 
	create_timestamp TIMESTAMP WITHOUT TIME ZONE, 
	update_user VARCHAR(60) DEFAULT 'system', 
	update_timestamp TIMESTAMP WITHOUT TIME ZONE, 
	deleted_ind BOOLEAN DEFAULT FALSE, 
	mine_report_req_permit_condition_xref_guid UUID NOT NULL, 
	mine_report_permit_requirement_id INTEGER, 
	permit_condition_id INTEGER, 
	transaction_id BIGINT NOT NULL, 
	end_transaction_id BIGINT, 
	operation_type SMALLINT NOT NULL, 
	PRIMARY KEY (mine_report_req_permit_condition_xref_guid, transaction_id)
);
CREATE INDEX ix_mine_report_req_permit_condition_xref_version_end_tr_fc37 ON mine_report_req_permit_condition_xref_version (end_transaction_id);
CREATE INDEX ix_mine_report_req_permit_condition_xref_version_operation_type ON mine_report_req_permit_condition_xref_version (operation_type);
CREATE INDEX ix_mine_report_req_permit_condition_xref_version_transaction_id ON mine_report_req_permit_condition_xref_version (transaction_id);
