-- This file was generated by the generate_history_table_ddl command
-- The file contains the corresponding history table definition for the {table} table
CREATE TABLE permit_condition_category_version (
	create_user VARCHAR(60), 
	create_timestamp TIMESTAMP WITHOUT TIME ZONE, 
	update_user VARCHAR(60), 
	update_timestamp TIMESTAMP WITHOUT TIME ZONE, 
	deleted_ind BOOLEAN, 
	condition_category_code VARCHAR NOT NULL, 
	step VARCHAR, 
	description VARCHAR, 
	active_ind BOOLEAN, 
	display_order INTEGER, 
	permit_amendment_id INTEGER, 
	transaction_id BIGINT NOT NULL, 
	end_transaction_id BIGINT, 
	operation_type SMALLINT NOT NULL, 
	PRIMARY KEY (condition_category_code, transaction_id)
);
CREATE INDEX ix_permit_condition_category_version_transaction_id ON permit_condition_category_version (transaction_id);
CREATE INDEX ix_permit_condition_category_version_end_transaction_id ON permit_condition_category_version (end_transaction_id);
CREATE INDEX ix_permit_condition_category_version_operation_type ON permit_condition_category_version (operation_type);
