-- This file was generated by the generate_history_table_ddl command
-- The file contains the corresponding history table definition for the {table} table
CREATE TABLE dam_version (
	create_user VARCHAR(60), 
	create_timestamp TIMESTAMP WITHOUT TIME ZONE, 
	update_user VARCHAR(60), 
	update_timestamp TIMESTAMP WITHOUT TIME ZONE, 
	deleted_ind BOOLEAN, 
	dam_guid UUID NOT NULL, 
	mine_tailings_storage_facility_guid UUID, 
	dam_type dam_type, 
	dam_name VARCHAR(200), 
	latitude NUMERIC(9, 7), 
	longitude NUMERIC(11, 7), 
	operating_status operating_status, 
	consequence_classification consequence_classification, 
	permitted_dam_crest_elevation NUMERIC(10, 2), 
	current_dam_height NUMERIC(10, 2), 
	current_elevation NUMERIC(10, 2), 
	max_pond_elevation NUMERIC(10, 2), 
	min_freeboard_required NUMERIC(10, 2), 
	transaction_id BIGINT NOT NULL, 
	end_transaction_id BIGINT, 
	operation_type SMALLINT NOT NULL, 
	PRIMARY KEY (dam_guid, transaction_id)
);
CREATE INDEX ix_dam_version_operation_type ON dam_version (operation_type);
CREATE INDEX ix_dam_version_transaction_id ON dam_version (transaction_id);
CREATE INDEX ix_dam_version_end_transaction_id ON dam_version (end_transaction_id);
