-- This file was generated by the generate_history_table_ddl command
-- The file contains the corresponding history table definition for the {table} table
CREATE TABLE ams_final_application_version (
	is_draft BOOLEAN, 
	create_user VARCHAR(60), 
	create_timestamp TIMESTAMP WITH TIME ZONE, 
	update_user VARCHAR(60), 
	update_timestamp TIMESTAMP WITH TIME ZONE, 
	deleted_ind BOOLEAN, 
	ams_final_application_guid UUID NOT NULL, 
	project_summary_authorization_guid UUID, 
	submitter_name VARCHAR(200), 
	is_agent BOOLEAN, 
	pre_submitted_files text[], 
	submitted_timestamp TIMESTAMP WITH TIME ZONE, 
	transaction_id BIGINT NOT NULL, 
	end_transaction_id BIGINT, 
	operation_type SMALLINT NOT NULL, 
	PRIMARY KEY (ams_final_application_guid, transaction_id)
);
CREATE INDEX ix_ams_final_application_version_transaction_id ON ams_final_application_version (transaction_id);
CREATE INDEX ix_ams_final_application_version_end_transaction_id ON ams_final_application_version (end_transaction_id);
CREATE INDEX ix_ams_final_application_version_operation_type ON ams_final_application_version (operation_type);
