-- This file was generated by the generate_history_table_ddl command
-- The file contains the data migration to backfill history records for the {table} table
with transaction AS (insert into transaction(id) values(DEFAULT) RETURNING id)
insert into mine_report_permit_requirement_version (transaction_id, operation_type, end_transaction_id, "create_user", "create_timestamp", "update_user", "update_timestamp", "deleted_ind", "mine_report_permit_requirement_id", "due_date_period_months", "initial_due_date", "report_name", "active_ind", "cim_or_cpo", "ministry_recipient", "permit_amendment_id")
select t.id, '0', null, "create_user", "create_timestamp", "update_user", "update_timestamp", "deleted_ind", "mine_report_permit_requirement_id", "due_date_period_months", "initial_due_date", "report_name", "active_ind", "cim_or_cpo", "ministry_recipient", "permit_amendment_id"
from mine_report_permit_requirement,transaction t;
