-- This file was generated by the generate_history_table_ddl command
-- The file contains the corresponding history table definition for the {table} table
CREATE TABLE user_version (
	create_user VARCHAR(60), 
	create_timestamp TIMESTAMP WITHOUT TIME ZONE, 
	update_user VARCHAR(60), 
	update_timestamp TIMESTAMP WITHOUT TIME ZONE, 
	deleted_ind BOOLEAN default FALSE,
	sub VARCHAR NOT NULL, 
	email VARCHAR, 
	given_name VARCHAR, 
	family_name VARCHAR, 
	display_name VARCHAR, 
	idir_username VARCHAR, 
	identity_provider VARCHAR, 
	idir_user_guid VARCHAR, 
	transaction_id BIGINT NOT NULL, 
	end_transaction_id BIGINT, 
	operation_type SMALLINT NOT NULL, 
	PRIMARY KEY (sub, transaction_id)
);
CREATE INDEX ix_user_version_operation_type ON user_version (operation_type);
CREATE INDEX ix_user_version_end_transaction_id ON user_version (end_transaction_id);
CREATE INDEX ix_user_version_transaction_id ON user_version (transaction_id);
