-- This file was generated by the generate_history_table_ddl command
-- The file contains the corresponding history table definition for the {table} table
CREATE TABLE now_application_tier_version (
	create_user VARCHAR(60), 
	create_timestamp TIMESTAMP WITHOUT TIME ZONE, 
	update_user VARCHAR(60), 
	update_timestamp TIMESTAMP WITHOUT TIME ZONE, 
	now_application_tier_id INTEGER NOT NULL, 
	now_application_id INTEGER, 
	notice_of_work_tier_code VARCHAR(3), 
	description VARCHAR, 
	transaction_id BIGINT NOT NULL, 
	end_transaction_id BIGINT, 
	operation_type SMALLINT NOT NULL, 
	PRIMARY KEY (now_application_tier_id, transaction_id)
);
CREATE INDEX ix_now_application_tier_version_operation_type ON now_application_tier_version (operation_type);
CREATE INDEX ix_now_application_tier_version_end_transaction_id ON now_application_tier_version (end_transaction_id);
CREATE INDEX ix_now_application_tier_version_transaction_id ON now_application_tier_version (transaction_id);
