-- This file was generated by the generate_history_table_ddl command
-- The file contains the data migration to backfill history records for the {table} table
with transaction AS (insert into transaction(id) values(DEFAULT) RETURNING id)
insert into mine_report_req_permit_condition_xref_version (transaction_id, operation_type, end_transaction_id, "create_user", "create_timestamp", "update_user", "update_timestamp", "deleted_ind", "mine_report_req_permit_condition_xref_guid", "mine_report_permit_requirement_id", "permit_condition_id")
select t.id, '0', null, "create_user", "create_timestamp", "update_user", "update_timestamp", "deleted_ind", "mine_report_req_permit_condition_xref_guid", "mine_report_permit_requirement_id", "permit_condition_id"
from mine_report_req_permit_condition_xref,transaction t;
