-- This file was generated by the generate_history_table_ddl command
-- The file contains the data migration to backfill history records for the {table} table
with transaction AS (insert into transaction(id) values(DEFAULT) RETURNING id)
insert into dam_version (transaction_id, operation_type, end_transaction_id, "create_user", "create_timestamp", "update_user", "update_timestamp", "deleted_ind", "dam_guid", "mine_tailings_storage_facility_guid", "dam_type", "dam_name", "latitude", "longitude", "operating_status", "consequence_classification", "permitted_dam_crest_elevation", "current_dam_height", "current_elevation", "max_pond_elevation", "min_freeboard_required")
select t.id, '0', null, "create_user", "create_timestamp", "update_user", "update_timestamp", "deleted_ind", "dam_guid", "mine_tailings_storage_facility_guid", "dam_type", "dam_name", "latitude", "longitude", "operating_status", "consequence_classification", "permitted_dam_crest_elevation", "current_dam_height", "current_elevation", "max_pond_elevation", "min_freeboard_required"
from dam,transaction t;
