-- This file was generated by the generate_history_table_ddl command
-- The file contains the data migration to backfill history records for the {table} table
with transaction AS (insert into transaction(id) values(DEFAULT) RETURNING id)
insert into permit_condition_category_version (transaction_id, operation_type, end_transaction_id, "create_user", "create_timestamp", "update_user", "update_timestamp", "deleted_ind", "condition_category_code", "step", "description", "active_ind", "display_order", "permit_amendment_id")
select t.id, '0', null, "create_user", "create_timestamp", "update_user", "update_timestamp", "deleted_ind", "condition_category_code", "step", "description", "active_ind", "display_order", "permit_amendment_id"
from permit_condition_category,transaction t;
