FROM "__FROM_IMAGE_STREAM_DEFINED_IN_TEMPLATE__"

RUN yum install -y \     
    libc6-dev \     
    libgdiplus \     
    libx11-dev \     
    curl \     
    vim \     
    supervisor \     
    procps     
