apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: mds-patroni
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: template
    app.kubernetes.io/name: patroni
    cluster-name: mds-patroni
  name: mds-patroni
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
  - delete
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - patch
  - update
  - create
  - list
  - watch
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - update
  - watch