# Copyright 2020 The Province of British Columbia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: |-
      Patroni Postgresql database cluster (prerequisites)
    iconClass: icon-postgresql
    openshift.io/display-name: Patroni Postgresql prerequisites
    openshift.io/long-description: This template deploys patroni prerequisites for an HA DB (secret, service account, role)
    tags: postgresql
  name: patroni-pgsql-pre-requisite
labels:
  app.kubernetes.io/component: database
  app.kubernetes.io/name: patroni
  app.kubernetes.io/managed-by: template
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      labels:
        app: ${NAME}
        cluster-name: ${NAME}
      name: ${NAME}-creds
    stringData:
      replication-username: ${PATRONI_REPLICATION_USERNAME}
      replication-password: ${PATRONI_REPLICATION_PASSWORD}
      superuser-username: ${PATRONI_SUPERUSER_USERNAME}
      superuser-password: ${PATRONI_SUPERUSER_PASSWORD}
      app-db-name: ${APP_DB_NAME}
      app-db-username: app_api_${APP_DB_USERNAME}
      app-db-password: ${APP_DB_PASSWORD}
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      labels:
        app: ${NAME}
        cluster-name: ${NAME}
      name: ${NAME}
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      labels:
        app: ${NAME}
        cluster-name: ${NAME}
      name: ${NAME}
    rules:
      - apiGroups:
          - ""
        resources:
          - services
        verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
          - delete
      - apiGroups:
          - ""
        resources:
          - configmaps
        verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
          - delete
      - apiGroups:
          - ""
        resources:
          - endpoints
        verbs:
          - get
          - patch
          - update
          - create
          - list
          - watch
          - delete
      - apiGroups:
          - ""
        resources:
          - pods
        verbs:
          - get
          - list
          - patch
          - update
          - watch
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      labels:
        app: ${NAME}
        cluster-name: ${NAME}
      name: ${NAME}
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: ${NAME}
    subjects:
      - kind: ServiceAccount
        name: ${NAME}
parameters:
  - name: NAME
    description: |
      The name of the application for labelling all artifacts.
    displayName: Application Name
    value: mycool-app-patroni
  - name: PATRONI_SUPERUSER_USERNAME
    description: |
      Username of the superuser account for initialization.
    displayName: Superuser Username
    value: postgres
  - name: PATRONI_SUPERUSER_PASSWORD
    description: |
      Password of the superuser account for initialization.
    displayName: Superuser Password
    generate: expression
    from: "[a-z0-9]{32}"
  - name: PATRONI_REPLICATION_USERNAME
    description: |
      Username of the replication account for initialization.
    displayName: Replication Username
    value: replication
  - name: PATRONI_REPLICATION_PASSWORD
    description: Password of the replication account for initialization.
    displayName: Replication Password
    generate: expression
    from: "[a-z0-9]{32}"
  - name: APP_DB_USERNAME
    generate: expression
    from: "[a-z0-9]{8}"
  - name: APP_DB_NAME
    value: registry
  - name: APP_DB_PASSWORD
    generate: expression
    from: "[a-z0-9]{32}"