apiVersion: v1
kind: Secret
metadata:
  labels:
    app: patroni
    cluster-name: patroni
  name: patroni-creds
stringData:
  replication-username: ${PATRONI_REPLICATION_USERNAME}
  replication-password: ${PATRONI_REPLICATION_PASSWORD}
  superuser-username: ${PATRONI_SUPERUSER_USERNAME}
  superuser-password: ${PATRONI_SUPERUSER_PASSWORD}
  app-db-name: ${APP_DB_NAME}
  app-db-username: app_api_${APP_DB_USERNAME}
  app-db-password: ${APP_DB_PASSWORD}
