// Redux Forms
export const ADD_REPORT = "ADD_REPORT";
export const EDIT_REPORT = "EDIT_REPORT";
export const ADD_VARIANCE = "ADD_VARIANCE";
export const EDIT_VARIANCE = "EDIT_VARIANCE";
export const ADD_MINE_WORK_INFORMATION = "ADD_MINE_WORK_INFORMATION";
export const EDIT_EMPLOYEE_COUNT = "EDIT_EMPLOYEE_COUNT_FORM";
export const ADD_TAILINGS = "ADD_TAILINGS";
export const ADD_INCIDENT = "ADD_INCIDENT";
export const ADD_EDIT_PROJECT_SUMMARY = "ADD_EDIT_PROJECT_SUMMARY";
