apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-web
  annotations:
    description: Defines how to deploy the application server
    template.alpha.openshift.io/wait-for-ready: "true"
  labels:
    component: core-web
    app.kubernetes.io/part-of: Core
    app.openshift.io/runtime: nodejs
    app.kubernetes.io/name: core-web
spec:
  strategy:
    type: RollingUpdate
    maxSurge: 50%
    maxUnavailable: 0
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      name: core-web
      service: core-web
  template:
    metadata:
      name: core-web
      labels:
        name: core-web
        app.kubernetes.io/name: core-web
        service: core-web
    spec:
      containers:
        - name: app
          image: "image-registry.openshift-image-registry.svc:5000/4c2ba9-tools/frontend:dev"
          env:
            - name: CORE_API_URL
              value: https://mds-dev.apps.silver.devops.gov.bc.ca/api
            - name: API_URL
              value: https://mds-dev.apps.silver.devops.gov.bc.ca/api
            - name: DOCUMENT_MANAGER_URL
              value: https://mds-dev.apps.silver.devops.gov.bc.ca/document-manager
            - name: MATOMO_URL
              value: https://matomo-4c2ba9-test.apps.silver.devops.gov.bc.ca/
            - name: TUSD_URL
              value: http://tusd:1080/files/
            - name: FN_LAYER_URL
              value: https://delivery.apps.gov.bc.ca/ext/sgw/geo.allgov
            - name: NODE_ENV
              value: development
            - name: BASE_PATH
              required: false
              value: ""
            - name: ASSET_PATH
              value: ${{BASE_PATH}}/
            - name: IMAGE_NAMESPACE
              value: 4c2ba9-tools
            - name: KEYCLOAK_RESOURCE
              value: mines-application-dev
            - name: KEYCLOAK_CLIENT_ID
              value: mines-application-dev
            - name: KEYCLOAK_URL
              value: https://test.oidc.gov.bc.ca/auth
            - name: KEYCLOAK_IDP_HINT
              value: idir
            - name: SITEMINDER_URL
              value: https://logontest7.gov.bc.ca
            - name: FILESYSTEM_PROVIDER_URL
              value: https://mds-dev.apps.silver.devops.gov.bc.ca/file-api/AmazonS3Provider/
            - name: APPLICATION_DOMAIN
              value: ""
          resources:
            limits:
              cpu: 60m
              memory: 600Mi
            requests:
              cpu:  20m
              memory: 200Mi
          ports:
            - containerPort: 3000
          livenessProbe:
            failureThreshold: 30
            httpGet:
              path: /health
              port: 3000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          readinessProbe:
            failureThreshold: 30
            httpGet:
              path: /health
              port: 3000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
