apiVersion: v1
kind: Service
metadata:
  name: core-web
  annotations:
    description: Exposes and load balances the application pods
  labels:
    app.kubernetes.io/part-of: Core
spec:
  ports:
    - name: web
      port: 3000
      targetPort: 3000
  selector:
    name: core-web