// Redux Forms
export const ADD_FULL_PARTY = "ADD_FULL_PARTY";
export const ADD_ROLES = "ADD_ROLES";
export const ADD_QUICK_PARTY = "ADD_QUICK_PARTY";
export const ADD_TENURE_NUMBER = "ADD_TENURE_NUMBER";
export const MINE_RECORD = "MINE_RECORD";
export const SEARCH_COORDINATES = "SEARCH_COORDINATES";
export const UPDATE_PERMITTEE = "UPDATE_PERMITTEE";
export const ADD_TAILINGS = "ADD_TAILINGS";
export const ADD_TAILINGS_REPORT = "ADD_TAILINGS_REPORT";
export const EDIT_TAILINGS = "EDIT_TAILINGS";
export const ADD_PARTY_RELATIONSHIP = "ADD_PARTY_RELATIONSHIP";
export const EDIT_PARTY_RELATIONSHIP = "EDIT_PARTY_RELATIONSHIP";
export const MINE_ADVANCED_SEARCH = "MINE_ADVANCED_SEARCH";
export const CONTACT_ADVANCED_SEARCH = "CONTACT_ADVANCE_SEARCH";
export const VARIANCE_ADVANCED_SEARCH = "VARIANCE_ADVANCED_SEARCH";
export const INCIDENT_ADVANCED_SEARCH = "INCIDENT_ADVANCED_SEARCH";
export const REPORT_ADVANCED_SEARCH = "REPORT_ADVANCED_SEARCH";
export const ADD_MINESPACE_USER = "ADD_MINESPACE_USER";
export const ADD_PERMIT = "ADD_PERMIT";
export const PERMIT_AMENDMENT = "PERMIT_AMENDMENT";
export const EDIT_PERMIT = "EDIT_PERMIT";
export const EDIT_FULL_PARTY = "EDIT_FULL_PARTY";
export const MINE_COMPLIANCE_FILTER = "MINE_COMPLIANCE_FILTER";
export const ADD_VARIANCE = "ADD_VARIANCE";
export const EDIT_VARIANCE = "EDIT_VARIANCE";
export const MINE_INCIDENT = "MINE_INCIDENT";
export const ADD_REPORT = "ADD_REPORT";
export const EDIT_REPORT = "EDIT_REPORT";
export const FILTER_REPORTS = "FILTER_REPORTS";
export const GENERATE_DOCUMENT = "GENERATE_DOCUMENT";

// Notice Of Work
export const NOTICE_OF_WORK_SEARCH = "NOTICE_OF_WORK_SEARCH";
export const EDIT_NOTICE_OF_WORK = "EDIT_NOTICE_OF_WORK";
export const EDIT_NOTICE_OF_WORK_DOCUMENT_FORM = "EDIT_NOTICE_OF_WORK_DOCUMENT_FORM";
export const CHANGE_NOW_MINE = "CHANGE_NOW_MINE";
export const UPDATE_NOW_LEAD_INSPECTOR = "UPDATE_NOW_LEAD_INSPECTOR";
export const UPDATE_NOW_STATUS = "UPDATE_NOW_STATUS";
export const ADD_NOW_REVIEW = "ADD_NOW_REVIEW";
export const MM_PERMIT_APPLICATION_CREATE = "MM_PERMIT_APPLICATION_CREATE";
export const CHANGE_NOW_LOCATION = "CHANGE_NOW_LOCATION";
export const MAJOR_MINE_PERMIT_APPLICATION_CREATE = "MAJOR_MINE_PERMIT_APPLICATION_CREATE";

// Securities
export const ADD_BOND = "ADD_BOND";
export const ADD_RECLAMATION_INVOICE = "ADD_RECLAMATION_INVOICE";

// Permit Generation
export const GENERATE_PERMIT = "GENERATE_PERMIT";
