// Documents
export const DOCUMENTS = "DOCUMENTS";
export const GENERATE_NOTICE_OF_WORK_APPLICATION_DOCUMENT =
  "GENERATE_NOTICE_OF_WORK_APPLICATION_DOCUMENT";
export const GET_NOTICE_OF_WORK_APPLICATION_DOCUMENT_CONTEXT_TEMPLATE =
  "GET_NOTICE_OF_WORK_APPLICATION_DOCUMENT_CONTEXT_TEMPLATE";
