"""empty message

Revision ID: 29b010bd6eb1
Revises: 
Create Date: 2019-05-23 21:33:45.406501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29b010bd6eb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_type',
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('document_type_id'),
    schema='nris'
    )
    op.create_table('inspection_status',
    sa.Column('inspection_status_id', sa.Integer(), nullable=False),
    sa.Column('inspection_status_code', sa.String(length=32), nullable=False),
    sa.Column('inspection_status_description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('inspection_status_id'),
    schema='nris'
    )
    op.create_table('legislation_act',
    sa.Column('legislation_act_id', sa.Integer(), nullable=False),
    sa.Column('act', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('legislation_act_id'),
    schema='nris'
    )
    op.create_table('legislation_compliance_article',
    sa.Column('legislation_compliance_article_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('legislation_compliance_article_id'),
    schema='nris'
    )
    op.create_table('location',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('latitude', sa.String(length=16), nullable=True),
    sa.Column('longitude', sa.String(length=16), nullable=True),
    sa.Column('utm_easting', sa.String(length=16), nullable=True),
    sa.Column('utm_northing', sa.String(length=16), nullable=True),
    sa.Column('zone_number', sa.String(length=8), nullable=True),
    sa.Column('zone_letter', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('location_id'),
    schema='nris'
    )
    op.create_table('nris_raw_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nris_data', sa.Text(), nullable=True),
    sa.Column('input_date', sa.DateTime(), nullable=False),
    sa.Column('processed_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='nris'
    )
    op.create_table('order_type',
    sa.Column('order_type_id', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('order_type_id'),
    schema='nris'
    )
    op.create_table('document',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('document_date', sa.DateTime(), nullable=True),
    sa.Column('document_type_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['document_type_id'], ['nris.document_type.document_type_id'], ),
    sa.PrimaryKeyConstraint('document_id'),
    schema='nris'
    )
    op.create_table('inspection',
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('inspection_date', sa.DateTime(), nullable=True),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('inspection_status_id', sa.Integer(), nullable=True),
    sa.Column('business_area', sa.String(length=256), nullable=True),
    sa.Column('mine_no', sa.String(length=64), nullable=True),
    sa.Column('inspector_idir', sa.String(length=256), nullable=True),
    sa.Column('inspection_introduction', sa.String(), nullable=True),
    sa.Column('inspection_preamble', sa.String(), nullable=True),
    sa.Column('inspection_closing', sa.String(), nullable=True),
    sa.Column('officer_notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_status_id'], ['nris.inspection_status.inspection_status_id'], ),
    sa.PrimaryKeyConstraint('inspection_id'),
    schema='nris'
    )
    op.create_table('legislation_act_section',
    sa.Column('legislation_act_section_id', sa.Integer(), nullable=False),
    sa.Column('legislation_act_id', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['legislation_act_id'], ['nris.legislation_act.legislation_act_id'], ),
    sa.PrimaryKeyConstraint('legislation_act_section_id'),
    schema='nris'
    )
    op.create_table('inspection_document_xref',
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['nris.document.document_id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['nris.inspection.inspection_id'], ),
    sa.PrimaryKeyConstraint('inspection_id', 'document_id'),
    schema='nris'
    )
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('order_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['nris.inspection.inspection_id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['nris.location.location_id'], ),
    sa.ForeignKeyConstraint(['order_type_id'], ['nris.order_type.order_type_id'], ),
    sa.PrimaryKeyConstraint('order_id'),
    schema='nris'
    )
    op.create_table('order_advisory_detail',
    sa.Column('order_advisory_detail_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['nris.order.order_id'], ),
    sa.PrimaryKeyConstraint('order_advisory_detail_id'),
    schema='nris'
    )
    op.create_table('order_document_xref',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['nris.document.document_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['nris.order.order_id'], ),
    sa.PrimaryKeyConstraint('order_id', 'document_id'),
    schema='nris'
    )
    op.create_table('order_request_detail',
    sa.Column('order_request_detail_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('response', sa.String(), nullable=True),
    sa.Column('respond_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['nris.order.order_id'], ),
    sa.PrimaryKeyConstraint('order_request_detail_id'),
    schema='nris'
    )
    op.create_table('order_stop_detail',
    sa.Column('order_stop_detail_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('stop_type', sa.String(length=256), nullable=True),
    sa.Column('response_status', sa.String(length=64), nullable=True),
    sa.Column('stop_status', sa.String(length=64), nullable=True),
    sa.Column('observation', sa.String(), nullable=True),
    sa.Column('response', sa.String(), nullable=True),
    sa.Column('response_received', sa.DateTime(), nullable=True),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.Column('authority_act', sa.String(length=64), nullable=True),
    sa.Column('authority_act_section', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['nris.order.order_id'], ),
    sa.PrimaryKeyConstraint('order_stop_detail_id'),
    schema='nris'
    )
    op.create_table('order_warning_detail',
    sa.Column('order_warning_detail_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('respond_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['nris.order.order_id'], ),
    sa.PrimaryKeyConstraint('order_warning_detail_id'),
    schema='nris'
    )
    op.create_table('legislation',
    sa.Column('legislation_id', sa.Integer(), nullable=False),
    sa.Column('order_stop_detail_id', sa.Integer(), nullable=True),
    sa.Column('estimated_incident_date', sa.DateTime(), nullable=True),
    sa.Column('noncompliant_description', sa.String(length=256), nullable=True),
    sa.Column('parent_act_id', sa.Integer(), nullable=True),
    sa.Column('legislation_act_section_id', sa.Integer(), nullable=True),
    sa.Column('complience_article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['complience_article_id'], ['nris.legislation_compliance_article.legislation_compliance_article_id'], ),
    sa.ForeignKeyConstraint(['legislation_act_section_id'], ['nris.legislation_act_section.legislation_act_section_id'], ),
    sa.ForeignKeyConstraint(['order_stop_detail_id'], ['nris.order_stop_detail.order_stop_detail_id'], ),
    sa.ForeignKeyConstraint(['parent_act_id'], ['nris.legislation_act.legislation_act_id'], ),
    sa.PrimaryKeyConstraint('legislation_id'),
    schema='nris'
    )
    op.create_table('order_stop_detail_document_xref',
    sa.Column('order_stop_detail_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['nris.document.document_id'], ),
    sa.ForeignKeyConstraint(['order_stop_detail_id'], ['nris.order_stop_detail.order_stop_detail_id'], ),
    sa.PrimaryKeyConstraint('order_stop_detail_id', 'document_id'),
    schema='nris'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_stop_detail_document_xref', schema='nris')
    op.drop_table('legislation', schema='nris')
    op.drop_table('order_warning_detail', schema='nris')
    op.drop_table('order_stop_detail', schema='nris')
    op.drop_table('order_request_detail', schema='nris')
    op.drop_table('order_document_xref', schema='nris')
    op.drop_table('order_advisory_detail', schema='nris')
    op.drop_table('order', schema='nris')
    op.drop_table('inspection_document_xref', schema='nris')
    op.drop_table('legislation_act_section', schema='nris')
    op.drop_table('inspection', schema='nris')
    op.drop_table('document', schema='nris')
    op.drop_table('order_type', schema='nris')
    op.drop_table('nris_raw_data', schema='nris')
    op.drop_table('location', schema='nris')
    op.drop_table('legislation_compliance_article', schema='nris')
    op.drop_table('legislation_act', schema='nris')
    op.drop_table('inspection_status', schema='nris')
    op.drop_table('document_type', schema='nris')
    # ### end Alembic commands ###
