"""empty message

Revision ID: 363b3042fef1
Revises: 3ae2902e6987
Create Date: 2019-05-22 17:12:05.621047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363b3042fef1'
down_revision = '3ae2902e6987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_advisory_detail',
    sa.Column('order_advisory_detail_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
    sa.PrimaryKeyConstraint('order_advisory_detail_id')
    )
    op.create_table('order_request_detail',
    sa.Column('order_request_detail_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(length=2048), nullable=True),
    sa.Column('response', sa.String(length=2048), nullable=True),
    sa.Column('respond_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
    sa.PrimaryKeyConstraint('order_request_detail_id')
    )
    op.create_table('order_stop_detail',
    sa.Column('order_stop_detail_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(length=2048), nullable=True),
    sa.Column('stop_type', sa.String(length=256), nullable=True),
    sa.Column('response_status', sa.String(length=64), nullable=True),
    sa.Column('stop_status', sa.String(length=64), nullable=True),
    sa.Column('observation', sa.String(length=2048), nullable=True),
    sa.Column('response', sa.String(length=2048), nullable=True),
    sa.Column('response_received', sa.DateTime(), nullable=True),
    sa.Column('authority_act', sa.String(length=64), nullable=True),
    sa.Column('authority_act_section', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
    sa.PrimaryKeyConstraint('order_stop_detail_id')
    )
    op.create_table('order_warning_detail',
    sa.Column('order_warning_detail_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(length=2048), nullable=True),
    sa.Column('respond_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
    sa.PrimaryKeyConstraint('order_warning_detail_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_warning_detail')
    op.drop_table('order_stop_detail')
    op.drop_table('order_request_detail')
    op.drop_table('order_advisory_detail')
    # ### end Alembic commands ###
