"""empty message

Revision ID: 67a55c71f4c6
Revises: 
Create Date: 2019-05-16 21:42:26.388434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67a55c71f4c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factorial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_val', sa.Integer(), nullable=False),
    sa.Column('output_val', sa.Integer(), nullable=False),
    sa.Column('exec_timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('input_val')
    )
    op.create_table('nris_raw_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nris_data', sa.Text(), nullable=True),
    sa.Column('input_date', sa.DateTime(), nullable=False),
    sa.Column('processed_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nris_raw_data')
    op.drop_table('factorial')
    # ### end Alembic commands ###
