"""empty message

Revision ID: 72047fbe36af
Revises: 
Create Date: 2019-05-13 17:20:08.166204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72047fbe36af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factorial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_val', sa.Integer(), nullable=False),
    sa.Column('output_val', sa.Integer(), nullable=False),
    sa.Column('exec_timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('input_val')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('factorial')
    # ### end Alembic commands ###
