"""empty message

Revision ID: a96d450a8cc3
Revises: fb359c2ed7cc
Create Date: 2019-10-09 21:38:07.673028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a96d450a8cc3'
down_revision = 'fb359c2ed7cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Attendee',
    sa.Column('attendee_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('org', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('attendee_id'),
    comment='Any attendee on an inspection.'
    )
    op.create_table('attendee_type',
    sa.Column('attendee_type_id', sa.Integer(), nullable=False),
    sa.Column('attendee_type', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('attendee_type_id'),
    comment='Lookup table that provides types of Attendees on an Inspection; i.e. Inspector, Management, FirstNations.'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendee_type')
    op.drop_table('Attendee')
    # ### end Alembic commands ###
