"""empty message

Revision ID: bf69217843fc
Revises: 72047fbe36af
Create Date: 2019-05-24 20:10:04.983085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf69217843fc'
down_revision = '72047fbe36af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_type',
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('document_type_id')
    )
    op.create_table('inspected_location_type',
    sa.Column('inspected_location_type_id', sa.Integer(), nullable=False),
    sa.Column('inspected_location_type', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('inspected_location_type_id')
    )
    op.create_table('inspection_status',
    sa.Column('inspection_status_id', sa.Integer(), nullable=False),
    sa.Column('inspection_status_code', sa.String(length=32), nullable=False),
    sa.Column('inspection_status_description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('inspection_status_id')
    )
    op.create_table('legislation_act',
    sa.Column('legislation_act_id', sa.Integer(), nullable=False),
    sa.Column('act', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('legislation_act_id')
    )
    op.create_table('legislation_compliance_article',
    sa.Column('legislation_compliance_article_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('legislation_compliance_article_id')
    )
    op.create_table('location',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('latitude', sa.String(length=16), nullable=True),
    sa.Column('longitude', sa.String(length=16), nullable=True),
    sa.Column('utm_easting', sa.String(length=16), nullable=True),
    sa.Column('utm_northing', sa.String(length=16), nullable=True),
    sa.Column('zone_number', sa.String(length=8), nullable=True),
    sa.Column('zone_letter', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('nris_raw_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nris_data', sa.Text(), nullable=True),
    sa.Column('input_date', sa.DateTime(), nullable=False),
    sa.Column('processed_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('document_date', sa.DateTime(), nullable=True),
    sa.Column('document_type_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=1024), nullable=True),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_type.document_type_id'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('inspection',
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('inspection_date', sa.DateTime(), nullable=True),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('inspection_status_id', sa.Integer(), nullable=True),
    sa.Column('business_area', sa.String(length=256), nullable=True),
    sa.Column('mine_no', sa.String(length=64), nullable=True),
    sa.Column('inspector_idir', sa.String(length=256), nullable=True),
    sa.Column('inspection_introduction', sa.String(), nullable=True),
    sa.Column('inspection_preamble', sa.String(), nullable=True),
    sa.Column('inspection_closing', sa.String(), nullable=True),
    sa.Column('officer_notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_status_id'], ['inspection_status.inspection_status_id'], ),
    sa.PrimaryKeyConstraint('inspection_id')
    )
    op.create_table('legislation_act_section',
    sa.Column('legislation_act_section_id', sa.Integer(), nullable=False),
    sa.Column('legislation_act_id', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['legislation_act_id'], ['legislation_act.legislation_act_id'], ),
    sa.PrimaryKeyConstraint('legislation_act_section_id')
    )
    op.create_table('inspected_location',
    sa.Column('inspected_location_id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('inspected_location_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inspected_location_type_id'], ['inspected_location_type.inspected_location_type_id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspection.inspection_id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], ),
    sa.PrimaryKeyConstraint('inspected_location_id')
    )
    op.create_table('inspection_document_xref',
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.document_id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspection.inspection_id'], ),
    sa.PrimaryKeyConstraint('inspection_id', 'document_id')
    )
    op.create_table('inspected_location_document_xref',
    sa.Column('inspected_location_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.document_id'], ),
    sa.ForeignKeyConstraint(['inspected_location_id'], ['inspected_location.inspected_location_id'], ),
    sa.PrimaryKeyConstraint('inspected_location_id', 'document_id')
    )
    op.create_table('order_advisory_detail',
    sa.Column('order_advisory_detail_id', sa.Integer(), nullable=False),
    sa.Column('inspected_locations_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['inspected_locations_id'], ['inspected_location.inspected_location_id'], ),
    sa.PrimaryKeyConstraint('order_advisory_detail_id')
    )
    op.create_table('order_request_detail',
    sa.Column('order_request_detail_id', sa.Integer(), nullable=False),
    sa.Column('inspected_location_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('response', sa.String(), nullable=True),
    sa.Column('respond_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inspected_location_id'], ['inspected_location.inspected_location_id'], ),
    sa.PrimaryKeyConstraint('order_request_detail_id')
    )
    op.create_table('order_stop_detail',
    sa.Column('order_stop_detail_id', sa.Integer(), nullable=False),
    sa.Column('inspected_location_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('stop_type', sa.String(length=256), nullable=True),
    sa.Column('response_status', sa.String(length=64), nullable=True),
    sa.Column('stop_status', sa.String(length=64), nullable=True),
    sa.Column('observation', sa.String(), nullable=True),
    sa.Column('response', sa.String(), nullable=True),
    sa.Column('response_received', sa.DateTime(), nullable=True),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.Column('authority_act', sa.String(length=64), nullable=True),
    sa.Column('authority_act_section', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['inspected_location_id'], ['inspected_location.inspected_location_id'], ),
    sa.PrimaryKeyConstraint('order_stop_detail_id')
    )
    op.create_table('order_warning_detail',
    sa.Column('order_warning_detail_id', sa.Integer(), nullable=False),
    sa.Column('inspected_location_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('respond_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inspected_location_id'], ['inspected_location.inspected_location_id'], ),
    sa.PrimaryKeyConstraint('order_warning_detail_id')
    )
    op.create_table('legislation',
    sa.Column('legislation_id', sa.Integer(), nullable=False),
    sa.Column('order_stop_detail_id', sa.Integer(), nullable=True),
    sa.Column('estimated_incident_date', sa.DateTime(), nullable=True),
    sa.Column('noncompliant_description', sa.String(length=256), nullable=True),
    sa.Column('parent_act_id', sa.Integer(), nullable=True),
    sa.Column('legislation_act_section_id', sa.Integer(), nullable=True),
    sa.Column('compliance_article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['compliance_article_id'], ['legislation_compliance_article.legislation_compliance_article_id'], ),
    sa.ForeignKeyConstraint(['legislation_act_section_id'], ['legislation_act_section.legislation_act_section_id'], ),
    sa.ForeignKeyConstraint(['order_stop_detail_id'], ['order_stop_detail.order_stop_detail_id'], ),
    sa.ForeignKeyConstraint(['parent_act_id'], ['legislation_act.legislation_act_id'], ),
    sa.PrimaryKeyConstraint('legislation_id')
    )
    op.create_table('order_stop_detail_document_xref',
    sa.Column('order_stop_detail_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.document_id'], ),
    sa.ForeignKeyConstraint(['order_stop_detail_id'], ['order_stop_detail.order_stop_detail_id'], ),
    sa.PrimaryKeyConstraint('order_stop_detail_id', 'document_id')
    )
    op.drop_table('factorial')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factorial',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('input_val', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('output_val', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exec_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='factorial_pkey'),
    sa.UniqueConstraint('input_val', name='factorial_input_val_key')
    )
    op.drop_table('order_stop_detail_document_xref')
    op.drop_table('legislation')
    op.drop_table('order_warning_detail')
    op.drop_table('order_stop_detail')
    op.drop_table('order_request_detail')
    op.drop_table('order_advisory_detail')
    op.drop_table('inspected_location_document_xref')
    op.drop_table('inspection_document_xref')
    op.drop_table('inspected_location')
    op.drop_table('legislation_act_section')
    op.drop_table('inspection')
    op.drop_table('document')
    op.drop_table('nris_raw_data')
    op.drop_table('location')
    op.drop_table('legislation_compliance_article')
    op.drop_table('legislation_act')
    op.drop_table('inspection_status')
    op.drop_table('inspected_location_type')
    op.drop_table('document_type')
    # ### end Alembic commands ###
