name: CORE API - Build & Deploy To DEV

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop
    paths:
      - services/core-web/**
      - .github/workflows/build-frontend.yaml

env:
  INITIAL_TAG: latest
  TAG: dev
  NAME: frontend
  CONTEXT: services/core-web/

jobs:
  build-backend:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login
        run: |
          docker login -u ${{ secrets.CLUSTER_REGISTRY_USER }} -p ${{ secrets.BUILD_TOKEN }} ${{ secrets.CLUSTER_REGISTRY }}
      - name: Build n Tag
        run: |
          docker build -t ${{ env.NAME }}:${{ env.INITIAL_TAG }} ${{ env.CONTEXT }} -f ${{ env.CONTEXT }}Dockerfile.ci
          docker tag ${{ env.NAME }}:${{ env.INITIAL_TAG }} ${{ secrets.CLUSTER_REGISTRY }}/${{ secrets.NS_TOOLS }}/${{ env.NAME }}:${{ env.INITIAL_TAG }}
          docker tag ${{ env.NAME }}:${{ env.INITIAL_TAG }} ${{ secrets.CLUSTER_REGISTRY }}/${{ secrets.NS_TOOLS }}/${{ env.NAME }}:${{ env.TAG }}
      - name: Push
        run: |
          docker push --all-tags ${{ secrets.CLUSTER_REGISTRY }}/${{ secrets.NS_TOOLS }}/${{ env.NAME }}

  trigger-gitops:
    runs-on: ubuntu-20.04
    needs: build-frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Git Ops Push
        run: ./gitops/commit.sh frontend dev ${{ secrets.GH_TOKEN }}
