name: Ensures redux common folders are the same
on: [pull_request]

jobs:
  common-folder-compare:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: compare-folders
        run: |
          diff -qr services/core-web/common services/minespace-web/common
          echo $?
          if [ $? ]
            then 
            echo "'/services/core-web/common' does not match '/services/minespace-web/common'"
            exit 1
          fi
