name: Ensures redux common folders are the same
on: [pull_request]

jobs:
  common-folder-compare:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: compare-folders
        run: |
          # pwd
          # CORE_COMMON_HASH=$(tar cf - services/core-web/common | md5sum)
          # echo $CORE_COMMON_HASH
          # MINESPACE_COMMON_HASH=$(tar cf - services/minespace-web/common | md5sum)
          # echo $MINESPACE_COMMON_HASH
          diff -qr services/core-web/common services/minespace-web/common
          if [ diff -qr services/core-web/common services/minespace-web/common ]
            then 
            echo "'/services/core-web/common' does not match '/services/minespace-web/common'"
            exit 1
          fi
