name: CORE WEB - Cypress Tests

on:
  pull_request:
    paths:
      - services/common/**
      - services/core-web/**

jobs:
  tests-unit-frontend:
    name: tests-cypress-core-web
    runs-on: ubuntu-20.04
    env:
      ELECTRON_EXTRA_LAUNCH_ARGS: '--disable-gpu'
    steps:
      - uses: actions/checkout@v3
        name: checkout
      
      - name: Retrieve environment variables
        run: |
          echo "CYPRESS_TEST_USER=${{ secrets.CYPRESS_TEST_USER }}"
          echo "CYPRESS_TEST_PASSWORD=${{ secrets.CYPRESS_TEST_PASSWORD }}"
          echo "CYPRESS_CORE_WEB_TEST_URL=${{ secrets.CYPRESS_CORE_WEB_TEST_URL }}"
          echo "CYPRESS_BACKEND=${{ secrets.CYPRESS_BACKEND }}"
          echo "CYPRESS_API_URL=${{ secrets.CYPRESS_API_URL }}"
          echo "CYPRESS_KEYCLOAK_URL=${{ secrets.CYPRESS_KEYCLOAK_URL }}"
          echo "CYPRESS_ENVIRONMENT=${{ secrets.CYPRESS_ENVIRONMENT }}"
          echo "CYPRESS_DOC_MAN_URL=${{ secrets.CYPRESS_DOC_MAN_URL }}"

      - uses: actions/cache@v3
        name: Cache yarn
        with:
          path: ./.yarn/cache
          key: mds-core-web
          restore-keys: mds-core-web

      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: yarn

      - name: Build Common Package
        run: cd services/common/ && yarn build

      - name: Run cypress tests
        run: cd services/core-web/ && yarn && yarn cypress run
