name: CORE WEB - Cypress Tests

on:
  pull_request:
    paths:
      - services/common/**
      - services/core-web/**

jobs:
  tests-unit-frontend:
    name: tests-cypress-frontend
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        name: checkout

      - uses: actions/cache@v3
        name: Cache yarn
        with:
          path: ./.yarn/cache
          key: mds-core-web
          restore-keys: mds-core-web

      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: yarn

      - name: Build Common Package
        run: cd services/common/ && yarn build

      - name: Run cypress tests
        run: cd services/core-web/ && yarn && yarn cypress run
