name: CORE WEB - Promote TEST

on:
  workflow_dispatch:

env:
  ORIG_TAG: dev
  PROMOTE_TAG: test

jobs:
  promote-image-to-test:
    name: promote-core-web-to-test
    runs-on: ubuntu-20.04
    steps:
      - name: Install oc
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: "4.7"

      - name: oc login
        run: |
          oc login --token=${{ secrets.BUILD_TOKEN }} --server=${{ secrets.CLUSTER_API }}

      - name: Promote core-web from dev to test
        run: |
          oc -n ${{secrets.NS_TOOLS}} tag \
          ${{ secrets.NS_TOOLS }}/frontend:${{ env.ORIG_TAG }} \
          ${{ secrets.NS_TOOLS }}/frontend:${{ env.PROMOTE_TAG }}
  
  # trigger-gitops:
  #   runs-on: ubuntu-20.04
  #   needs: build-frontend
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Git Ops Push
  #       run: ./gitops/commit.sh core-api dev test ${{ github.actor }} ${{ secrets.GH_TOKEN }}