name: Permit Service - Build & Deploy To DEV

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - services/permits/**
      - .github/workflows/permit-service.build.deploy.dev.yaml

env:
  INITIAL_TAG: latest
  TAG: dev
  NAME: permits
  CONTEXT: services/permits/

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          reguistry: ${{ secrets.CLUSTER_REGISTRY }}
          username: ${{ secrets.CLUSTER_REGISTRY_USER }}
          password: ${{ secrets.BUILD_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.CLUSTER_REGISTRY }}/${{ secrets.NS_TOOLS }}/${{ env.NAME }}:${{ env.INITIAL_TAG }},${{ secrets.CLUSTER_REGISTRY }}/${{ secrets.NS_TOOLS }}/${{ env.NAME }}:${{ env.TAG }}
          context: ${{ env.CONTEXT }}
