name: Permit Service - Build & Deploy To DEV

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - services/permits/**
      - .github/workflows/permit-service.build.deploy.dev.yaml

env:
  INITIAL_TAG: latest
  TAG: dev
  NAME: permits
  CONTEXT: services/permits/

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Openshift iamge registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ARTIFACTORY_CLUSTER_REGISTRY }}
          username: ${{ secrets.ARTIFACTORY_USER }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.ARTIFACTORY_CLUSTER_REGISTRY }}/${{ secrets.ARTIFACTORY_PROJECT_NAME }}/${{ env.NAME }}:${{ env.INITIAL_TAG }},${{ secrets.ARTIFACTORY_CLUSTER_REGISTRY }}/${{ secrets.ARTIFACTORY_PROJECT_NAME }}/${{ env.NAME }}:${{ env.TAG }}
          context: ${{ env.CONTEXT }}
