name: Decorate PR with Definition of Done
on:
  pull_request:

jobs:
  pr-checklist-comment:
    runs-on: ubuntu-latest

    steps:
      - uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          msg: "Definition of Done Reminders \n- [ ] Did you update associated documentation? \n- [ ] Has the PO or business delegate signed off on the changes? \n- [ ] If there are API changes, are they backwards compatible for consumers?"
