name: SchemaSpy - TEST restart rollout

on:
  workflow_call:
  workflow_dispatch:

jobs:
  dev-schemaspy-rollout:
    uses: ./.github/workflows/schemaspy-rollout.yaml    
    with: 
      environment: test
    secrets: inherit