name: Unit Tests

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  tests-unit-frontend:
    name: tests-unit-frontend
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Run frontend tests
        run: |
          cd services/core-web/ && npm ci && npm run test

  tests-unit-minespace:
    name: tests-unit-minespace
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Run minespace tests
        run: |
          cd services/minespace-web/ && npm ci && npm run test
