name: Integration Tests

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  tests-verify-migrations:
    name: tests-verify-migrations
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Check migrations successful
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker-compose -f docker-compose.ci.yaml up --exit-code-from flyway-verify flyway-verify

  tests-integration-backend:
    name: tests-integration-backend
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Create containers for integration tests
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker-compose -f docker-compose.ci.yaml up -d backend

      - name: Run integration tests
        run: |
          docker-compose -f docker-compose.ci.yaml exec -T backend pytest
