name: oc installer test

on:
  push:
  workflow_dispatch:

jobs:

  test-oc-installer:
    name: test-oc-installer
    runs-on: ubuntu-20.04
    steps:
      - name: Install oc
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: "4.7"
      - name: oc login
        run: |
          oc login --token=${{ secrets.BUILD_TOKEN }} --server=${{ secrets.CLUSTER_API }}