name: Build tusd

on: 
  pull_request:
  push:
    branches:
      - develop
    path:
      - migrations/**
      - .github/workflows/tusd.yaml

env:
  INITAL_TAG: latest
  TAG: dev
  NAME: tusd
  CONTEXT: services/tusd/

jobs:
  build-tusd:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login
        run: |
          docker login -u ${{ secrets.CLUSTER_REGISTRY_USER }} -p ${{ secrets.BUILD_TOKEN }} ${{ secrets.CLUSTER_REGISTRY }}
      - name: Build n Tag
        run: |
          docker build -t ${{ env.NAME }} ${{ env.CONTEXT }} -f ${{ env.CONTEXT }}Dockerfile.ci
          docker tag ${{ env.NAME }}:${{ env.INITIAL_TAG }} ${{ secrets.CLUSTER_REGISTRY }}/${{ secrets.NS_TOOLS }}/${{ env.NAME }}:${{ env.INITIAL_TAG }}
          docker tag ${{ env.NAME }}:${{ env.INITIAL_TAG }} ${{ secrets.CLUSTER_REGISTRY }}/${{ secrets.NS_TOOLS }}/${{ env.NAME }}:${{ env.TAG }}
      - name: Push
        run: |
          docker push --all-tags ${{ secrets.CLUSTER_REGISTRY }}/${{ secrets.NS_TOOLS }}/${{ env.NAME }}
