name: Core API - ZAP Scan

on:
  schedule:
    - cron: "0 8 * * *" # Runs at 08:00 UTC (Midnight PST)
  workflow_dispatch:
  pull_request:
    branches:
      - develop

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: ZAP API Full Scan
        uses: zaproxy/action-api-scan@v0.9.0
        with:
          target: "https://mds-test.apps.silver.devops.gov.bc.ca/api/swagger.json"
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: coreapi-zap-scan

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-core-api-report
          path: report_html.html
